package com.zyxy.common.domain;

import java.io.Serializable;
import java.util.Date;

public class CaseAvoidRecord implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_avoid_record.ID
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_avoid_record.CASE_ID
	 * @mbggenerated
	 */
	private String caseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_avoid_record.AVOID_ID
	 * @mbggenerated
	 */
	private String avoidId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_avoid_record.AVOID_TYPE
	 * @mbggenerated
	 */
	private String avoidType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_avoid_record.AVOID_STYLE
	 * @mbggenerated
	 */
	private String avoidStyle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_avoid_record.STATUS
	 * @mbggenerated
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_avoid_record.CREATER_ID
	 * @mbggenerated
	 */
	private String createrId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_avoid_record.CREATE_TIME
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_avoid_record.ID
	 * @return  the value of case_avoid_record.ID
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_avoid_record.ID
	 * @param id  the value for case_avoid_record.ID
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_avoid_record.CASE_ID
	 * @return  the value of case_avoid_record.CASE_ID
	 * @mbggenerated
	 */
	public String getCaseId() {
		return caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_avoid_record.CASE_ID
	 * @param caseId  the value for case_avoid_record.CASE_ID
	 * @mbggenerated
	 */
	public void setCaseId(String caseId) {
		this.caseId = caseId == null ? null : caseId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_avoid_record.AVOID_ID
	 * @return  the value of case_avoid_record.AVOID_ID
	 * @mbggenerated
	 */
	public String getAvoidId() {
		return avoidId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_avoid_record.AVOID_ID
	 * @param avoidId  the value for case_avoid_record.AVOID_ID
	 * @mbggenerated
	 */
	public void setAvoidId(String avoidId) {
		this.avoidId = avoidId == null ? null : avoidId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_avoid_record.AVOID_TYPE
	 * @return  the value of case_avoid_record.AVOID_TYPE
	 * @mbggenerated
	 */
	public String getAvoidType() {
		return avoidType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_avoid_record.AVOID_TYPE
	 * @param avoidType  the value for case_avoid_record.AVOID_TYPE
	 * @mbggenerated
	 */
	public void setAvoidType(String avoidType) {
		this.avoidType = avoidType == null ? null : avoidType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_avoid_record.AVOID_STYLE
	 * @return  the value of case_avoid_record.AVOID_STYLE
	 * @mbggenerated
	 */
	public String getAvoidStyle() {
		return avoidStyle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_avoid_record.AVOID_STYLE
	 * @param avoidStyle  the value for case_avoid_record.AVOID_STYLE
	 * @mbggenerated
	 */
	public void setAvoidStyle(String avoidStyle) {
		this.avoidStyle = avoidStyle == null ? null : avoidStyle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_avoid_record.STATUS
	 * @return  the value of case_avoid_record.STATUS
	 * @mbggenerated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_avoid_record.STATUS
	 * @param status  the value for case_avoid_record.STATUS
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_avoid_record.CREATER_ID
	 * @return  the value of case_avoid_record.CREATER_ID
	 * @mbggenerated
	 */
	public String getCreaterId() {
		return createrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_avoid_record.CREATER_ID
	 * @param createrId  the value for case_avoid_record.CREATER_ID
	 * @mbggenerated
	 */
	public void setCreaterId(String createrId) {
		this.createrId = createrId == null ? null : createrId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_avoid_record.CREATE_TIME
	 * @return  the value of case_avoid_record.CREATE_TIME
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_avoid_record.CREATE_TIME
	 * @param createTime  the value for case_avoid_record.CREATE_TIME
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}