package com.zyxy.common.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CaseAgentAuthorRecordExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	public CaseAgentAuthorRecordExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCaseIdIsNull() {
			addCriterion("CASE_ID is null");
			return (Criteria) this;
		}

		public Criteria andCaseIdIsNotNull() {
			addCriterion("CASE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCaseIdEqualTo(String value) {
			addCriterion("CASE_ID =", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotEqualTo(String value) {
			addCriterion("CASE_ID <>", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdGreaterThan(String value) {
			addCriterion("CASE_ID >", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdGreaterThanOrEqualTo(String value) {
			addCriterion("CASE_ID >=", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLessThan(String value) {
			addCriterion("CASE_ID <", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLessThanOrEqualTo(String value) {
			addCriterion("CASE_ID <=", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLike(String value) {
			addCriterion("CASE_ID like", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotLike(String value) {
			addCriterion("CASE_ID not like", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdIn(List<String> values) {
			addCriterion("CASE_ID in", values, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotIn(List<String> values) {
			addCriterion("CASE_ID not in", values, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdBetween(String value1, String value2) {
			addCriterion("CASE_ID between", value1, value2, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotBetween(String value1, String value2) {
			addCriterion("CASE_ID not between", value1, value2, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseNoIsNull() {
			addCriterion("CASE_NO is null");
			return (Criteria) this;
		}

		public Criteria andCaseNoIsNotNull() {
			addCriterion("CASE_NO is not null");
			return (Criteria) this;
		}

		public Criteria andCaseNoEqualTo(String value) {
			addCriterion("CASE_NO =", value, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoNotEqualTo(String value) {
			addCriterion("CASE_NO <>", value, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoGreaterThan(String value) {
			addCriterion("CASE_NO >", value, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoGreaterThanOrEqualTo(String value) {
			addCriterion("CASE_NO >=", value, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoLessThan(String value) {
			addCriterion("CASE_NO <", value, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoLessThanOrEqualTo(String value) {
			addCriterion("CASE_NO <=", value, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoLike(String value) {
			addCriterion("CASE_NO like", value, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoNotLike(String value) {
			addCriterion("CASE_NO not like", value, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoIn(List<String> values) {
			addCriterion("CASE_NO in", values, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoNotIn(List<String> values) {
			addCriterion("CASE_NO not in", values, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoBetween(String value1, String value2) {
			addCriterion("CASE_NO between", value1, value2, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoNotBetween(String value1, String value2) {
			addCriterion("CASE_NO not between", value1, value2, "caseNo");
			return (Criteria) this;
		}

		public Criteria andBusinessCodeIsNull() {
			addCriterion("BUSINESS_CODE is null");
			return (Criteria) this;
		}

		public Criteria andBusinessCodeIsNotNull() {
			addCriterion("BUSINESS_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andBusinessCodeEqualTo(String value) {
			addCriterion("BUSINESS_CODE =", value, "businessCode");
			return (Criteria) this;
		}

		public Criteria andBusinessCodeNotEqualTo(String value) {
			addCriterion("BUSINESS_CODE <>", value, "businessCode");
			return (Criteria) this;
		}

		public Criteria andBusinessCodeGreaterThan(String value) {
			addCriterion("BUSINESS_CODE >", value, "businessCode");
			return (Criteria) this;
		}

		public Criteria andBusinessCodeGreaterThanOrEqualTo(String value) {
			addCriterion("BUSINESS_CODE >=", value, "businessCode");
			return (Criteria) this;
		}

		public Criteria andBusinessCodeLessThan(String value) {
			addCriterion("BUSINESS_CODE <", value, "businessCode");
			return (Criteria) this;
		}

		public Criteria andBusinessCodeLessThanOrEqualTo(String value) {
			addCriterion("BUSINESS_CODE <=", value, "businessCode");
			return (Criteria) this;
		}

		public Criteria andBusinessCodeLike(String value) {
			addCriterion("BUSINESS_CODE like", value, "businessCode");
			return (Criteria) this;
		}

		public Criteria andBusinessCodeNotLike(String value) {
			addCriterion("BUSINESS_CODE not like", value, "businessCode");
			return (Criteria) this;
		}

		public Criteria andBusinessCodeIn(List<String> values) {
			addCriterion("BUSINESS_CODE in", values, "businessCode");
			return (Criteria) this;
		}

		public Criteria andBusinessCodeNotIn(List<String> values) {
			addCriterion("BUSINESS_CODE not in", values, "businessCode");
			return (Criteria) this;
		}

		public Criteria andBusinessCodeBetween(String value1, String value2) {
			addCriterion("BUSINESS_CODE between", value1, value2,
					"businessCode");
			return (Criteria) this;
		}

		public Criteria andBusinessCodeNotBetween(String value1, String value2) {
			addCriterion("BUSINESS_CODE not between", value1, value2,
					"businessCode");
			return (Criteria) this;
		}

		public Criteria andAgentTypeIsNull() {
			addCriterion("AGENT_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andAgentTypeIsNotNull() {
			addCriterion("AGENT_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andAgentTypeEqualTo(String value) {
			addCriterion("AGENT_TYPE =", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeNotEqualTo(String value) {
			addCriterion("AGENT_TYPE <>", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeGreaterThan(String value) {
			addCriterion("AGENT_TYPE >", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeGreaterThanOrEqualTo(String value) {
			addCriterion("AGENT_TYPE >=", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeLessThan(String value) {
			addCriterion("AGENT_TYPE <", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeLessThanOrEqualTo(String value) {
			addCriterion("AGENT_TYPE <=", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeLike(String value) {
			addCriterion("AGENT_TYPE like", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeNotLike(String value) {
			addCriterion("AGENT_TYPE not like", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeIn(List<String> values) {
			addCriterion("AGENT_TYPE in", values, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeNotIn(List<String> values) {
			addCriterion("AGENT_TYPE not in", values, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeBetween(String value1, String value2) {
			addCriterion("AGENT_TYPE between", value1, value2, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeNotBetween(String value1, String value2) {
			addCriterion("AGENT_TYPE not between", value1, value2, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentStyleIsNull() {
			addCriterion("AGENT_STYLE is null");
			return (Criteria) this;
		}

		public Criteria andAgentStyleIsNotNull() {
			addCriterion("AGENT_STYLE is not null");
			return (Criteria) this;
		}

		public Criteria andAgentStyleEqualTo(String value) {
			addCriterion("AGENT_STYLE =", value, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleNotEqualTo(String value) {
			addCriterion("AGENT_STYLE <>", value, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleGreaterThan(String value) {
			addCriterion("AGENT_STYLE >", value, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleGreaterThanOrEqualTo(String value) {
			addCriterion("AGENT_STYLE >=", value, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleLessThan(String value) {
			addCriterion("AGENT_STYLE <", value, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleLessThanOrEqualTo(String value) {
			addCriterion("AGENT_STYLE <=", value, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleLike(String value) {
			addCriterion("AGENT_STYLE like", value, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleNotLike(String value) {
			addCriterion("AGENT_STYLE not like", value, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleIn(List<String> values) {
			addCriterion("AGENT_STYLE in", values, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleNotIn(List<String> values) {
			addCriterion("AGENT_STYLE not in", values, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleBetween(String value1, String value2) {
			addCriterion("AGENT_STYLE between", value1, value2, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleNotBetween(String value1, String value2) {
			addCriterion("AGENT_STYLE not between", value1, value2,
					"agentStyle");
			return (Criteria) this;
		}

		public Criteria andAccptNameIsNull() {
			addCriterion("ACCPT_NAME is null");
			return (Criteria) this;
		}

		public Criteria andAccptNameIsNotNull() {
			addCriterion("ACCPT_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andAccptNameEqualTo(String value) {
			addCriterion("ACCPT_NAME =", value, "accptName");
			return (Criteria) this;
		}

		public Criteria andAccptNameNotEqualTo(String value) {
			addCriterion("ACCPT_NAME <>", value, "accptName");
			return (Criteria) this;
		}

		public Criteria andAccptNameGreaterThan(String value) {
			addCriterion("ACCPT_NAME >", value, "accptName");
			return (Criteria) this;
		}

		public Criteria andAccptNameGreaterThanOrEqualTo(String value) {
			addCriterion("ACCPT_NAME >=", value, "accptName");
			return (Criteria) this;
		}

		public Criteria andAccptNameLessThan(String value) {
			addCriterion("ACCPT_NAME <", value, "accptName");
			return (Criteria) this;
		}

		public Criteria andAccptNameLessThanOrEqualTo(String value) {
			addCriterion("ACCPT_NAME <=", value, "accptName");
			return (Criteria) this;
		}

		public Criteria andAccptNameLike(String value) {
			addCriterion("ACCPT_NAME like", value, "accptName");
			return (Criteria) this;
		}

		public Criteria andAccptNameNotLike(String value) {
			addCriterion("ACCPT_NAME not like", value, "accptName");
			return (Criteria) this;
		}

		public Criteria andAccptNameIn(List<String> values) {
			addCriterion("ACCPT_NAME in", values, "accptName");
			return (Criteria) this;
		}

		public Criteria andAccptNameNotIn(List<String> values) {
			addCriterion("ACCPT_NAME not in", values, "accptName");
			return (Criteria) this;
		}

		public Criteria andAccptNameBetween(String value1, String value2) {
			addCriterion("ACCPT_NAME between", value1, value2, "accptName");
			return (Criteria) this;
		}

		public Criteria andAccptNameNotBetween(String value1, String value2) {
			addCriterion("ACCPT_NAME not between", value1, value2, "accptName");
			return (Criteria) this;
		}

		public Criteria andAccptCardIdIsNull() {
			addCriterion("ACCPT_CARD_ID is null");
			return (Criteria) this;
		}

		public Criteria andAccptCardIdIsNotNull() {
			addCriterion("ACCPT_CARD_ID is not null");
			return (Criteria) this;
		}

		public Criteria andAccptCardIdEqualTo(String value) {
			addCriterion("ACCPT_CARD_ID =", value, "accptCardId");
			return (Criteria) this;
		}

		public Criteria andAccptCardIdNotEqualTo(String value) {
			addCriterion("ACCPT_CARD_ID <>", value, "accptCardId");
			return (Criteria) this;
		}

		public Criteria andAccptCardIdGreaterThan(String value) {
			addCriterion("ACCPT_CARD_ID >", value, "accptCardId");
			return (Criteria) this;
		}

		public Criteria andAccptCardIdGreaterThanOrEqualTo(String value) {
			addCriterion("ACCPT_CARD_ID >=", value, "accptCardId");
			return (Criteria) this;
		}

		public Criteria andAccptCardIdLessThan(String value) {
			addCriterion("ACCPT_CARD_ID <", value, "accptCardId");
			return (Criteria) this;
		}

		public Criteria andAccptCardIdLessThanOrEqualTo(String value) {
			addCriterion("ACCPT_CARD_ID <=", value, "accptCardId");
			return (Criteria) this;
		}

		public Criteria andAccptCardIdLike(String value) {
			addCriterion("ACCPT_CARD_ID like", value, "accptCardId");
			return (Criteria) this;
		}

		public Criteria andAccptCardIdNotLike(String value) {
			addCriterion("ACCPT_CARD_ID not like", value, "accptCardId");
			return (Criteria) this;
		}

		public Criteria andAccptCardIdIn(List<String> values) {
			addCriterion("ACCPT_CARD_ID in", values, "accptCardId");
			return (Criteria) this;
		}

		public Criteria andAccptCardIdNotIn(List<String> values) {
			addCriterion("ACCPT_CARD_ID not in", values, "accptCardId");
			return (Criteria) this;
		}

		public Criteria andAccptCardIdBetween(String value1, String value2) {
			addCriterion("ACCPT_CARD_ID between", value1, value2, "accptCardId");
			return (Criteria) this;
		}

		public Criteria andAccptCardIdNotBetween(String value1, String value2) {
			addCriterion("ACCPT_CARD_ID not between", value1, value2,
					"accptCardId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdIsNull() {
			addCriterion("CASE_TYPE_ID is null");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdIsNotNull() {
			addCriterion("CASE_TYPE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdEqualTo(String value) {
			addCriterion("CASE_TYPE_ID =", value, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdNotEqualTo(String value) {
			addCriterion("CASE_TYPE_ID <>", value, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdGreaterThan(String value) {
			addCriterion("CASE_TYPE_ID >", value, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdGreaterThanOrEqualTo(String value) {
			addCriterion("CASE_TYPE_ID >=", value, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdLessThan(String value) {
			addCriterion("CASE_TYPE_ID <", value, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdLessThanOrEqualTo(String value) {
			addCriterion("CASE_TYPE_ID <=", value, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdLike(String value) {
			addCriterion("CASE_TYPE_ID like", value, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdNotLike(String value) {
			addCriterion("CASE_TYPE_ID not like", value, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdIn(List<String> values) {
			addCriterion("CASE_TYPE_ID in", values, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdNotIn(List<String> values) {
			addCriterion("CASE_TYPE_ID not in", values, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdBetween(String value1, String value2) {
			addCriterion("CASE_TYPE_ID between", value1, value2, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdNotBetween(String value1, String value2) {
			addCriterion("CASE_TYPE_ID not between", value1, value2,
					"caseTypeId");
			return (Criteria) this;
		}

		public Criteria andDutiesIsNull() {
			addCriterion("DUTIES is null");
			return (Criteria) this;
		}

		public Criteria andDutiesIsNotNull() {
			addCriterion("DUTIES is not null");
			return (Criteria) this;
		}

		public Criteria andDutiesEqualTo(String value) {
			addCriterion("DUTIES =", value, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesNotEqualTo(String value) {
			addCriterion("DUTIES <>", value, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesGreaterThan(String value) {
			addCriterion("DUTIES >", value, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesGreaterThanOrEqualTo(String value) {
			addCriterion("DUTIES >=", value, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesLessThan(String value) {
			addCriterion("DUTIES <", value, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesLessThanOrEqualTo(String value) {
			addCriterion("DUTIES <=", value, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesLike(String value) {
			addCriterion("DUTIES like", value, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesNotLike(String value) {
			addCriterion("DUTIES not like", value, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesIn(List<String> values) {
			addCriterion("DUTIES in", values, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesNotIn(List<String> values) {
			addCriterion("DUTIES not in", values, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesBetween(String value1, String value2) {
			addCriterion("DUTIES between", value1, value2, "duties");
			return (Criteria) this;
		}

		public Criteria andDutiesNotBetween(String value1, String value2) {
			addCriterion("DUTIES not between", value1, value2, "duties");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIsNull() {
			addCriterion("CREATER_ID is null");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIsNotNull() {
			addCriterion("CREATER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCreaterIdEqualTo(String value) {
			addCriterion("CREATER_ID =", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotEqualTo(String value) {
			addCriterion("CREATER_ID <>", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdGreaterThan(String value) {
			addCriterion("CREATER_ID >", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdGreaterThanOrEqualTo(String value) {
			addCriterion("CREATER_ID >=", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLessThan(String value) {
			addCriterion("CREATER_ID <", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLessThanOrEqualTo(String value) {
			addCriterion("CREATER_ID <=", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLike(String value) {
			addCriterion("CREATER_ID like", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotLike(String value) {
			addCriterion("CREATER_ID not like", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIn(List<String> values) {
			addCriterion("CREATER_ID in", values, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotIn(List<String> values) {
			addCriterion("CREATER_ID not in", values, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdBetween(String value1, String value2) {
			addCriterion("CREATER_ID between", value1, value2, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotBetween(String value1, String value2) {
			addCriterion("CREATER_ID not between", value1, value2, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andRequestTypeIsNull() {
			addCriterion("REQUEST_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andRequestTypeIsNotNull() {
			addCriterion("REQUEST_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andRequestTypeEqualTo(String value) {
			addCriterion("REQUEST_TYPE =", value, "requestType");
			return (Criteria) this;
		}

		public Criteria andRequestTypeNotEqualTo(String value) {
			addCriterion("REQUEST_TYPE <>", value, "requestType");
			return (Criteria) this;
		}

		public Criteria andRequestTypeGreaterThan(String value) {
			addCriterion("REQUEST_TYPE >", value, "requestType");
			return (Criteria) this;
		}

		public Criteria andRequestTypeGreaterThanOrEqualTo(String value) {
			addCriterion("REQUEST_TYPE >=", value, "requestType");
			return (Criteria) this;
		}

		public Criteria andRequestTypeLessThan(String value) {
			addCriterion("REQUEST_TYPE <", value, "requestType");
			return (Criteria) this;
		}

		public Criteria andRequestTypeLessThanOrEqualTo(String value) {
			addCriterion("REQUEST_TYPE <=", value, "requestType");
			return (Criteria) this;
		}

		public Criteria andRequestTypeLike(String value) {
			addCriterion("REQUEST_TYPE like", value, "requestType");
			return (Criteria) this;
		}

		public Criteria andRequestTypeNotLike(String value) {
			addCriterion("REQUEST_TYPE not like", value, "requestType");
			return (Criteria) this;
		}

		public Criteria andRequestTypeIn(List<String> values) {
			addCriterion("REQUEST_TYPE in", values, "requestType");
			return (Criteria) this;
		}

		public Criteria andRequestTypeNotIn(List<String> values) {
			addCriterion("REQUEST_TYPE not in", values, "requestType");
			return (Criteria) this;
		}

		public Criteria andRequestTypeBetween(String value1, String value2) {
			addCriterion("REQUEST_TYPE between", value1, value2, "requestType");
			return (Criteria) this;
		}

		public Criteria andRequestTypeNotBetween(String value1, String value2) {
			addCriterion("REQUEST_TYPE not between", value1, value2,
					"requestType");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table case_agent_author_record
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}