package com.zyxy.common.domain;

import java.io.Serializable;
import java.util.Date;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * @author tanquan
 *
 * case_info
 *
 * @mbggenerated do_not_delete_during_merge
 */
@ApiModel(value ="CaseInfo")
public class CaseInfo implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "编号")
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.CASE_NO
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "案号")
	private String caseNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.ACCEPTANCE_NO
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "收案号")
	private String acceptanceNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.CASE_TYPE_ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "案件类型描述")
	private String caseTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.CURRENT_MAIN_NODE
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "当前主流程节点")
	private Integer currentMainNode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.CURRENT_CHILD_NODE
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "当前子流程节点")
	private Integer currentChildNode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.STATUS
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "案件状态 ")
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.SOURCE_ORG_ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "案件来源（与api_orgnazation.id关联），null-本系统")
	private String sourceOrgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.CREATER_ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "创建者ID")
	private String createrId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.CREATE_TIME
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "创建时间")
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.UPDATE_TIME
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "更新时间")
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.REGISTER_TIME
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "立案时间")
	private Date registerTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.UPDATE_ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "")
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.ACCEPT_TIME
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "接案时间（仲裁员接案时间）")
	private Date acceptTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.CURRENT_OWNER
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "当前责任人，用户编号")
	private String currentOwner;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.COMPLETE_TIME
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "结案时间")
	private Date completeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.APPLY_TYPE
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "立案人类型，0- 本人，1- 代理")
	private String applyType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.CASE_ACCEPTANCE_TIME
	 * @mbggenerated
	 */
	private Date caseAcceptanceTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.SIGN_ABRI_PROTOCOL_MODE
	 * @mbggenerated
	 */
	private String signAbriProtocolMode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.SIGN_TIME
	 * @mbggenerated
	 */
	private Date signTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_info.PROTOCOL_NAME
	 * @mbggenerated
	 */
	private String protocolName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_info
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.ID
	 * @return  the value of case_info.ID
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.ID
	 * @param id  the value for case_info.ID
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.CASE_NO
	 * @return  the value of case_info.CASE_NO
	 * @mbggenerated
	 */
	public String getCaseNo() {
		return caseNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.CASE_NO
	 * @param caseNo  the value for case_info.CASE_NO
	 * @mbggenerated
	 */
	public void setCaseNo(String caseNo) {
		this.caseNo = caseNo == null ? null : caseNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.ACCEPTANCE_NO
	 * @return  the value of case_info.ACCEPTANCE_NO
	 * @mbggenerated
	 */
	public String getAcceptanceNo() {
		return acceptanceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.ACCEPTANCE_NO
	 * @param acceptanceNo  the value for case_info.ACCEPTANCE_NO
	 * @mbggenerated
	 */
	public void setAcceptanceNo(String acceptanceNo) {
		this.acceptanceNo = acceptanceNo == null ? null : acceptanceNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.CASE_TYPE_ID
	 * @return  the value of case_info.CASE_TYPE_ID
	 * @mbggenerated
	 */
	public String getCaseTypeId() {
		return caseTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.CASE_TYPE_ID
	 * @param caseTypeId  the value for case_info.CASE_TYPE_ID
	 * @mbggenerated
	 */
	public void setCaseTypeId(String caseTypeId) {
		this.caseTypeId = caseTypeId == null ? null : caseTypeId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.CURRENT_MAIN_NODE
	 * @return  the value of case_info.CURRENT_MAIN_NODE
	 * @mbggenerated
	 */
	public Integer getCurrentMainNode() {
		return currentMainNode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.CURRENT_MAIN_NODE
	 * @param currentMainNode  the value for case_info.CURRENT_MAIN_NODE
	 * @mbggenerated
	 */
	public void setCurrentMainNode(Integer currentMainNode) {
		this.currentMainNode = currentMainNode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.CURRENT_CHILD_NODE
	 * @return  the value of case_info.CURRENT_CHILD_NODE
	 * @mbggenerated
	 */
	public Integer getCurrentChildNode() {
		return currentChildNode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.CURRENT_CHILD_NODE
	 * @param currentChildNode  the value for case_info.CURRENT_CHILD_NODE
	 * @mbggenerated
	 */
	public void setCurrentChildNode(Integer currentChildNode) {
		this.currentChildNode = currentChildNode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.STATUS
	 * @return  the value of case_info.STATUS
	 * @mbggenerated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.STATUS
	 * @param status  the value for case_info.STATUS
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.SOURCE_ORG_ID
	 * @return  the value of case_info.SOURCE_ORG_ID
	 * @mbggenerated
	 */
	public String getSourceOrgId() {
		return sourceOrgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.SOURCE_ORG_ID
	 * @param sourceOrgId  the value for case_info.SOURCE_ORG_ID
	 * @mbggenerated
	 */
	public void setSourceOrgId(String sourceOrgId) {
		this.sourceOrgId = sourceOrgId == null ? null : sourceOrgId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.CREATER_ID
	 * @return  the value of case_info.CREATER_ID
	 * @mbggenerated
	 */
	public String getCreaterId() {
		return createrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.CREATER_ID
	 * @param createrId  the value for case_info.CREATER_ID
	 * @mbggenerated
	 */
	public void setCreaterId(String createrId) {
		this.createrId = createrId == null ? null : createrId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.CREATE_TIME
	 * @return  the value of case_info.CREATE_TIME
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.CREATE_TIME
	 * @param createTime  the value for case_info.CREATE_TIME
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.UPDATE_TIME
	 * @return  the value of case_info.UPDATE_TIME
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.UPDATE_TIME
	 * @param updateTime  the value for case_info.UPDATE_TIME
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.REGISTER_TIME
	 * @return  the value of case_info.REGISTER_TIME
	 * @mbggenerated
	 */
	public Date getRegisterTime() {
		return registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.REGISTER_TIME
	 * @param registerTime  the value for case_info.REGISTER_TIME
	 * @mbggenerated
	 */
	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.UPDATE_ID
	 * @return  the value of case_info.UPDATE_ID
	 * @mbggenerated
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.UPDATE_ID
	 * @param updateId  the value for case_info.UPDATE_ID
	 * @mbggenerated
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId == null ? null : updateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.ACCEPT_TIME
	 * @return  the value of case_info.ACCEPT_TIME
	 * @mbggenerated
	 */
	public Date getAcceptTime() {
		return acceptTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.ACCEPT_TIME
	 * @param acceptTime  the value for case_info.ACCEPT_TIME
	 * @mbggenerated
	 */
	public void setAcceptTime(Date acceptTime) {
		this.acceptTime = acceptTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.CURRENT_OWNER
	 * @return  the value of case_info.CURRENT_OWNER
	 * @mbggenerated
	 */
	public String getCurrentOwner() {
		return currentOwner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.CURRENT_OWNER
	 * @param currentOwner  the value for case_info.CURRENT_OWNER
	 * @mbggenerated
	 */
	public void setCurrentOwner(String currentOwner) {
		this.currentOwner = currentOwner == null ? null : currentOwner.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.COMPLETE_TIME
	 * @return  the value of case_info.COMPLETE_TIME
	 * @mbggenerated
	 */
	public Date getCompleteTime() {
		return completeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.COMPLETE_TIME
	 * @param completeTime  the value for case_info.COMPLETE_TIME
	 * @mbggenerated
	 */
	public void setCompleteTime(Date completeTime) {
		this.completeTime = completeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.APPLY_TYPE
	 * @return  the value of case_info.APPLY_TYPE
	 * @mbggenerated
	 */
	public String getApplyType() {
		return applyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.APPLY_TYPE
	 * @param applyType  the value for case_info.APPLY_TYPE
	 * @mbggenerated
	 */
	public void setApplyType(String applyType) {
		this.applyType = applyType == null ? null : applyType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.CASE_ACCEPTANCE_TIME
	 * @return  the value of case_info.CASE_ACCEPTANCE_TIME
	 * @mbggenerated
	 */
	public Date getCaseAcceptanceTime() {
		return caseAcceptanceTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.CASE_ACCEPTANCE_TIME
	 * @param caseAcceptanceTime  the value for case_info.CASE_ACCEPTANCE_TIME
	 * @mbggenerated
	 */
	public void setCaseAcceptanceTime(Date caseAcceptanceTime) {
		this.caseAcceptanceTime = caseAcceptanceTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.SIGN_ABRI_PROTOCOL_MODE
	 * @return  the value of case_info.SIGN_ABRI_PROTOCOL_MODE
	 * @mbggenerated
	 */
	public String getSignAbriProtocolMode() {
		return signAbriProtocolMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.SIGN_ABRI_PROTOCOL_MODE
	 * @param signAbriProtocolMode  the value for case_info.SIGN_ABRI_PROTOCOL_MODE
	 * @mbggenerated
	 */
	public void setSignAbriProtocolMode(String signAbriProtocolMode) {
		this.signAbriProtocolMode = signAbriProtocolMode == null ? null
				: signAbriProtocolMode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.SIGN_TIME
	 * @return  the value of case_info.SIGN_TIME
	 * @mbggenerated
	 */
	public Date getSignTime() {
		return signTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.SIGN_TIME
	 * @param signTime  the value for case_info.SIGN_TIME
	 * @mbggenerated
	 */
	public void setSignTime(Date signTime) {
		this.signTime = signTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_info.PROTOCOL_NAME
	 * @return  the value of case_info.PROTOCOL_NAME
	 * @mbggenerated
	 */
	public String getProtocolName() {
		return protocolName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_info.PROTOCOL_NAME
	 * @param protocolName  the value for case_info.PROTOCOL_NAME
	 * @mbggenerated
	 */
	public void setProtocolName(String protocolName) {
		this.protocolName = protocolName == null ? null : protocolName.trim();
	}


}