package com.zyxy.common.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CaseAgentExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_agent
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_agent
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_agent
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent
	 * @mbggenerated
	 */
	public CaseAgentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table case_agent
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCaseIdIsNull() {
			addCriterion("CASE_ID is null");
			return (Criteria) this;
		}

		public Criteria andCaseIdIsNotNull() {
			addCriterion("CASE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCaseIdEqualTo(String value) {
			addCriterion("CASE_ID =", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotEqualTo(String value) {
			addCriterion("CASE_ID <>", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdGreaterThan(String value) {
			addCriterion("CASE_ID >", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdGreaterThanOrEqualTo(String value) {
			addCriterion("CASE_ID >=", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLessThan(String value) {
			addCriterion("CASE_ID <", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLessThanOrEqualTo(String value) {
			addCriterion("CASE_ID <=", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLike(String value) {
			addCriterion("CASE_ID like", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotLike(String value) {
			addCriterion("CASE_ID not like", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdIn(List<String> values) {
			addCriterion("CASE_ID in", values, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotIn(List<String> values) {
			addCriterion("CASE_ID not in", values, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdBetween(String value1, String value2) {
			addCriterion("CASE_ID between", value1, value2, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotBetween(String value1, String value2) {
			addCriterion("CASE_ID not between", value1, value2, "caseId");
			return (Criteria) this;
		}

		public Criteria andLitigantTypeIsNull() {
			addCriterion("LITIGANT_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andLitigantTypeIsNotNull() {
			addCriterion("LITIGANT_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andLitigantTypeEqualTo(String value) {
			addCriterion("LITIGANT_TYPE =", value, "litigantType");
			return (Criteria) this;
		}

		public Criteria andLitigantTypeNotEqualTo(String value) {
			addCriterion("LITIGANT_TYPE <>", value, "litigantType");
			return (Criteria) this;
		}

		public Criteria andLitigantTypeGreaterThan(String value) {
			addCriterion("LITIGANT_TYPE >", value, "litigantType");
			return (Criteria) this;
		}

		public Criteria andLitigantTypeGreaterThanOrEqualTo(String value) {
			addCriterion("LITIGANT_TYPE >=", value, "litigantType");
			return (Criteria) this;
		}

		public Criteria andLitigantTypeLessThan(String value) {
			addCriterion("LITIGANT_TYPE <", value, "litigantType");
			return (Criteria) this;
		}

		public Criteria andLitigantTypeLessThanOrEqualTo(String value) {
			addCriterion("LITIGANT_TYPE <=", value, "litigantType");
			return (Criteria) this;
		}

		public Criteria andLitigantTypeLike(String value) {
			addCriterion("LITIGANT_TYPE like", value, "litigantType");
			return (Criteria) this;
		}

		public Criteria andLitigantTypeNotLike(String value) {
			addCriterion("LITIGANT_TYPE not like", value, "litigantType");
			return (Criteria) this;
		}

		public Criteria andLitigantTypeIn(List<String> values) {
			addCriterion("LITIGANT_TYPE in", values, "litigantType");
			return (Criteria) this;
		}

		public Criteria andLitigantTypeNotIn(List<String> values) {
			addCriterion("LITIGANT_TYPE not in", values, "litigantType");
			return (Criteria) this;
		}

		public Criteria andLitigantTypeBetween(String value1, String value2) {
			addCriterion("LITIGANT_TYPE between", value1, value2,
					"litigantType");
			return (Criteria) this;
		}

		public Criteria andLitigantTypeNotBetween(String value1, String value2) {
			addCriterion("LITIGANT_TYPE not between", value1, value2,
					"litigantType");
			return (Criteria) this;
		}

		public Criteria andAgentIdIsNull() {
			addCriterion("AGENT_ID is null");
			return (Criteria) this;
		}

		public Criteria andAgentIdIsNotNull() {
			addCriterion("AGENT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andAgentIdEqualTo(String value) {
			addCriterion("AGENT_ID =", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdNotEqualTo(String value) {
			addCriterion("AGENT_ID <>", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdGreaterThan(String value) {
			addCriterion("AGENT_ID >", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdGreaterThanOrEqualTo(String value) {
			addCriterion("AGENT_ID >=", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdLessThan(String value) {
			addCriterion("AGENT_ID <", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdLessThanOrEqualTo(String value) {
			addCriterion("AGENT_ID <=", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdLike(String value) {
			addCriterion("AGENT_ID like", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdNotLike(String value) {
			addCriterion("AGENT_ID not like", value, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdIn(List<String> values) {
			addCriterion("AGENT_ID in", values, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdNotIn(List<String> values) {
			addCriterion("AGENT_ID not in", values, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdBetween(String value1, String value2) {
			addCriterion("AGENT_ID between", value1, value2, "agentId");
			return (Criteria) this;
		}

		public Criteria andAgentIdNotBetween(String value1, String value2) {
			addCriterion("AGENT_ID not between", value1, value2, "agentId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIsNull() {
			addCriterion("CREATER_ID is null");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIsNotNull() {
			addCriterion("CREATER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCreaterIdEqualTo(String value) {
			addCriterion("CREATER_ID =", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotEqualTo(String value) {
			addCriterion("CREATER_ID <>", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdGreaterThan(String value) {
			addCriterion("CREATER_ID >", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdGreaterThanOrEqualTo(String value) {
			addCriterion("CREATER_ID >=", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLessThan(String value) {
			addCriterion("CREATER_ID <", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLessThanOrEqualTo(String value) {
			addCriterion("CREATER_ID <=", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLike(String value) {
			addCriterion("CREATER_ID like", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotLike(String value) {
			addCriterion("CREATER_ID not like", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIn(List<String> values) {
			addCriterion("CREATER_ID in", values, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotIn(List<String> values) {
			addCriterion("CREATER_ID not in", values, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdBetween(String value1, String value2) {
			addCriterion("CREATER_ID between", value1, value2, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotBetween(String value1, String value2) {
			addCriterion("CREATER_ID not between", value1, value2, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateIdIsNull() {
			addCriterion("UPDATE_ID is null");
			return (Criteria) this;
		}

		public Criteria andUpdateIdIsNotNull() {
			addCriterion("UPDATE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateIdEqualTo(String value) {
			addCriterion("UPDATE_ID =", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotEqualTo(String value) {
			addCriterion("UPDATE_ID <>", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdGreaterThan(String value) {
			addCriterion("UPDATE_ID >", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_ID >=", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdLessThan(String value) {
			addCriterion("UPDATE_ID <", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_ID <=", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdLike(String value) {
			addCriterion("UPDATE_ID like", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotLike(String value) {
			addCriterion("UPDATE_ID not like", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdIn(List<String> values) {
			addCriterion("UPDATE_ID in", values, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotIn(List<String> values) {
			addCriterion("UPDATE_ID not in", values, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdBetween(String value1, String value2) {
			addCriterion("UPDATE_ID between", value1, value2, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotBetween(String value1, String value2) {
			addCriterion("UPDATE_ID not between", value1, value2, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("UPDATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("UPDATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("UPDATE_TIME =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("UPDATE_TIME <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("UPDATE_TIME >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("UPDATE_TIME <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("UPDATE_TIME in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("UPDATE_TIME not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andAgentTypeIsNull() {
			addCriterion("AGENT_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andAgentTypeIsNotNull() {
			addCriterion("AGENT_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andAgentTypeEqualTo(String value) {
			addCriterion("AGENT_TYPE =", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeNotEqualTo(String value) {
			addCriterion("AGENT_TYPE <>", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeGreaterThan(String value) {
			addCriterion("AGENT_TYPE >", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeGreaterThanOrEqualTo(String value) {
			addCriterion("AGENT_TYPE >=", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeLessThan(String value) {
			addCriterion("AGENT_TYPE <", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeLessThanOrEqualTo(String value) {
			addCriterion("AGENT_TYPE <=", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeLike(String value) {
			addCriterion("AGENT_TYPE like", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeNotLike(String value) {
			addCriterion("AGENT_TYPE not like", value, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeIn(List<String> values) {
			addCriterion("AGENT_TYPE in", values, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeNotIn(List<String> values) {
			addCriterion("AGENT_TYPE not in", values, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeBetween(String value1, String value2) {
			addCriterion("AGENT_TYPE between", value1, value2, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentTypeNotBetween(String value1, String value2) {
			addCriterion("AGENT_TYPE not between", value1, value2, "agentType");
			return (Criteria) this;
		}

		public Criteria andAgentStyleIsNull() {
			addCriterion("AGENT_STYLE is null");
			return (Criteria) this;
		}

		public Criteria andAgentStyleIsNotNull() {
			addCriterion("AGENT_STYLE is not null");
			return (Criteria) this;
		}

		public Criteria andAgentStyleEqualTo(String value) {
			addCriterion("AGENT_STYLE =", value, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleNotEqualTo(String value) {
			addCriterion("AGENT_STYLE <>", value, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleGreaterThan(String value) {
			addCriterion("AGENT_STYLE >", value, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleGreaterThanOrEqualTo(String value) {
			addCriterion("AGENT_STYLE >=", value, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleLessThan(String value) {
			addCriterion("AGENT_STYLE <", value, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleLessThanOrEqualTo(String value) {
			addCriterion("AGENT_STYLE <=", value, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleLike(String value) {
			addCriterion("AGENT_STYLE like", value, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleNotLike(String value) {
			addCriterion("AGENT_STYLE not like", value, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleIn(List<String> values) {
			addCriterion("AGENT_STYLE in", values, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleNotIn(List<String> values) {
			addCriterion("AGENT_STYLE not in", values, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleBetween(String value1, String value2) {
			addCriterion("AGENT_STYLE between", value1, value2, "agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentStyleNotBetween(String value1, String value2) {
			addCriterion("AGENT_STYLE not between", value1, value2,
					"agentStyle");
			return (Criteria) this;
		}

		public Criteria andAgentOccupationIsNull() {
			addCriterion("AGENT_OCCUPATION is null");
			return (Criteria) this;
		}

		public Criteria andAgentOccupationIsNotNull() {
			addCriterion("AGENT_OCCUPATION is not null");
			return (Criteria) this;
		}

		public Criteria andAgentOccupationEqualTo(String value) {
			addCriterion("AGENT_OCCUPATION =", value, "agentOccupation");
			return (Criteria) this;
		}

		public Criteria andAgentOccupationNotEqualTo(String value) {
			addCriterion("AGENT_OCCUPATION <>", value, "agentOccupation");
			return (Criteria) this;
		}

		public Criteria andAgentOccupationGreaterThan(String value) {
			addCriterion("AGENT_OCCUPATION >", value, "agentOccupation");
			return (Criteria) this;
		}

		public Criteria andAgentOccupationGreaterThanOrEqualTo(String value) {
			addCriterion("AGENT_OCCUPATION >=", value, "agentOccupation");
			return (Criteria) this;
		}

		public Criteria andAgentOccupationLessThan(String value) {
			addCriterion("AGENT_OCCUPATION <", value, "agentOccupation");
			return (Criteria) this;
		}

		public Criteria andAgentOccupationLessThanOrEqualTo(String value) {
			addCriterion("AGENT_OCCUPATION <=", value, "agentOccupation");
			return (Criteria) this;
		}

		public Criteria andAgentOccupationLike(String value) {
			addCriterion("AGENT_OCCUPATION like", value, "agentOccupation");
			return (Criteria) this;
		}

		public Criteria andAgentOccupationNotLike(String value) {
			addCriterion("AGENT_OCCUPATION not like", value, "agentOccupation");
			return (Criteria) this;
		}

		public Criteria andAgentOccupationIn(List<String> values) {
			addCriterion("AGENT_OCCUPATION in", values, "agentOccupation");
			return (Criteria) this;
		}

		public Criteria andAgentOccupationNotIn(List<String> values) {
			addCriterion("AGENT_OCCUPATION not in", values, "agentOccupation");
			return (Criteria) this;
		}

		public Criteria andAgentOccupationBetween(String value1, String value2) {
			addCriterion("AGENT_OCCUPATION between", value1, value2,
					"agentOccupation");
			return (Criteria) this;
		}

		public Criteria andAgentOccupationNotBetween(String value1,
				String value2) {
			addCriterion("AGENT_OCCUPATION not between", value1, value2,
					"agentOccupation");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table case_agent
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table case_agent
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}