package com.zyxy.common.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CaseInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_info
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_info
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_info
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_info
	 * @mbggenerated
	 */
	public CaseInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_info
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_info
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_info
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_info
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_info
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_info
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_info
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_info
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_info
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_info
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table case_info
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCaseNoIsNull() {
			addCriterion("CASE_NO is null");
			return (Criteria) this;
		}

		public Criteria andCaseNoIsNotNull() {
			addCriterion("CASE_NO is not null");
			return (Criteria) this;
		}

		public Criteria andCaseNoEqualTo(String value) {
			addCriterion("CASE_NO =", value, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoNotEqualTo(String value) {
			addCriterion("CASE_NO <>", value, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoGreaterThan(String value) {
			addCriterion("CASE_NO >", value, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoGreaterThanOrEqualTo(String value) {
			addCriterion("CASE_NO >=", value, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoLessThan(String value) {
			addCriterion("CASE_NO <", value, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoLessThanOrEqualTo(String value) {
			addCriterion("CASE_NO <=", value, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoLike(String value) {
			addCriterion("CASE_NO like", value, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoNotLike(String value) {
			addCriterion("CASE_NO not like", value, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoIn(List<String> values) {
			addCriterion("CASE_NO in", values, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoNotIn(List<String> values) {
			addCriterion("CASE_NO not in", values, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoBetween(String value1, String value2) {
			addCriterion("CASE_NO between", value1, value2, "caseNo");
			return (Criteria) this;
		}

		public Criteria andCaseNoNotBetween(String value1, String value2) {
			addCriterion("CASE_NO not between", value1, value2, "caseNo");
			return (Criteria) this;
		}

		public Criteria andAcceptanceNoIsNull() {
			addCriterion("ACCEPTANCE_NO is null");
			return (Criteria) this;
		}

		public Criteria andAcceptanceNoIsNotNull() {
			addCriterion("ACCEPTANCE_NO is not null");
			return (Criteria) this;
		}

		public Criteria andAcceptanceNoEqualTo(String value) {
			addCriterion("ACCEPTANCE_NO =", value, "acceptanceNo");
			return (Criteria) this;
		}

		public Criteria andAcceptanceNoNotEqualTo(String value) {
			addCriterion("ACCEPTANCE_NO <>", value, "acceptanceNo");
			return (Criteria) this;
		}

		public Criteria andAcceptanceNoGreaterThan(String value) {
			addCriterion("ACCEPTANCE_NO >", value, "acceptanceNo");
			return (Criteria) this;
		}

		public Criteria andAcceptanceNoGreaterThanOrEqualTo(String value) {
			addCriterion("ACCEPTANCE_NO >=", value, "acceptanceNo");
			return (Criteria) this;
		}

		public Criteria andAcceptanceNoLessThan(String value) {
			addCriterion("ACCEPTANCE_NO <", value, "acceptanceNo");
			return (Criteria) this;
		}

		public Criteria andAcceptanceNoLessThanOrEqualTo(String value) {
			addCriterion("ACCEPTANCE_NO <=", value, "acceptanceNo");
			return (Criteria) this;
		}

		public Criteria andAcceptanceNoLike(String value) {
			addCriterion("ACCEPTANCE_NO like", value, "acceptanceNo");
			return (Criteria) this;
		}

		public Criteria andAcceptanceNoNotLike(String value) {
			addCriterion("ACCEPTANCE_NO not like", value, "acceptanceNo");
			return (Criteria) this;
		}

		public Criteria andAcceptanceNoIn(List<String> values) {
			addCriterion("ACCEPTANCE_NO in", values, "acceptanceNo");
			return (Criteria) this;
		}

		public Criteria andAcceptanceNoNotIn(List<String> values) {
			addCriterion("ACCEPTANCE_NO not in", values, "acceptanceNo");
			return (Criteria) this;
		}

		public Criteria andAcceptanceNoBetween(String value1, String value2) {
			addCriterion("ACCEPTANCE_NO between", value1, value2,
					"acceptanceNo");
			return (Criteria) this;
		}

		public Criteria andAcceptanceNoNotBetween(String value1, String value2) {
			addCriterion("ACCEPTANCE_NO not between", value1, value2,
					"acceptanceNo");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdIsNull() {
			addCriterion("CASE_TYPE_ID is null");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdIsNotNull() {
			addCriterion("CASE_TYPE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdEqualTo(String value) {
			addCriterion("CASE_TYPE_ID =", value, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdNotEqualTo(String value) {
			addCriterion("CASE_TYPE_ID <>", value, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdGreaterThan(String value) {
			addCriterion("CASE_TYPE_ID >", value, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdGreaterThanOrEqualTo(String value) {
			addCriterion("CASE_TYPE_ID >=", value, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdLessThan(String value) {
			addCriterion("CASE_TYPE_ID <", value, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdLessThanOrEqualTo(String value) {
			addCriterion("CASE_TYPE_ID <=", value, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdLike(String value) {
			addCriterion("CASE_TYPE_ID like", value, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdNotLike(String value) {
			addCriterion("CASE_TYPE_ID not like", value, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdIn(List<String> values) {
			addCriterion("CASE_TYPE_ID in", values, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdNotIn(List<String> values) {
			addCriterion("CASE_TYPE_ID not in", values, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdBetween(String value1, String value2) {
			addCriterion("CASE_TYPE_ID between", value1, value2, "caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCaseTypeIdNotBetween(String value1, String value2) {
			addCriterion("CASE_TYPE_ID not between", value1, value2,
					"caseTypeId");
			return (Criteria) this;
		}

		public Criteria andCurrentMainNodeIsNull() {
			addCriterion("CURRENT_MAIN_NODE is null");
			return (Criteria) this;
		}

		public Criteria andCurrentMainNodeIsNotNull() {
			addCriterion("CURRENT_MAIN_NODE is not null");
			return (Criteria) this;
		}

		public Criteria andCurrentMainNodeEqualTo(Integer value) {
			addCriterion("CURRENT_MAIN_NODE =", value, "currentMainNode");
			return (Criteria) this;
		}

		public Criteria andCurrentMainNodeNotEqualTo(Integer value) {
			addCriterion("CURRENT_MAIN_NODE <>", value, "currentMainNode");
			return (Criteria) this;
		}

		public Criteria andCurrentMainNodeGreaterThan(Integer value) {
			addCriterion("CURRENT_MAIN_NODE >", value, "currentMainNode");
			return (Criteria) this;
		}

		public Criteria andCurrentMainNodeGreaterThanOrEqualTo(Integer value) {
			addCriterion("CURRENT_MAIN_NODE >=", value, "currentMainNode");
			return (Criteria) this;
		}

		public Criteria andCurrentMainNodeLessThan(Integer value) {
			addCriterion("CURRENT_MAIN_NODE <", value, "currentMainNode");
			return (Criteria) this;
		}

		public Criteria andCurrentMainNodeLessThanOrEqualTo(Integer value) {
			addCriterion("CURRENT_MAIN_NODE <=", value, "currentMainNode");
			return (Criteria) this;
		}

		public Criteria andCurrentMainNodeIn(List<Integer> values) {
			addCriterion("CURRENT_MAIN_NODE in", values, "currentMainNode");
			return (Criteria) this;
		}

		public Criteria andCurrentMainNodeNotIn(List<Integer> values) {
			addCriterion("CURRENT_MAIN_NODE not in", values, "currentMainNode");
			return (Criteria) this;
		}

		public Criteria andCurrentMainNodeBetween(Integer value1, Integer value2) {
			addCriterion("CURRENT_MAIN_NODE between", value1, value2,
					"currentMainNode");
			return (Criteria) this;
		}

		public Criteria andCurrentMainNodeNotBetween(Integer value1,
				Integer value2) {
			addCriterion("CURRENT_MAIN_NODE not between", value1, value2,
					"currentMainNode");
			return (Criteria) this;
		}

		public Criteria andCurrentChildNodeIsNull() {
			addCriterion("CURRENT_CHILD_NODE is null");
			return (Criteria) this;
		}

		public Criteria andCurrentChildNodeIsNotNull() {
			addCriterion("CURRENT_CHILD_NODE is not null");
			return (Criteria) this;
		}

		public Criteria andCurrentChildNodeEqualTo(Integer value) {
			addCriterion("CURRENT_CHILD_NODE =", value, "currentChildNode");
			return (Criteria) this;
		}

		public Criteria andCurrentChildNodeNotEqualTo(Integer value) {
			addCriterion("CURRENT_CHILD_NODE <>", value, "currentChildNode");
			return (Criteria) this;
		}

		public Criteria andCurrentChildNodeGreaterThan(Integer value) {
			addCriterion("CURRENT_CHILD_NODE >", value, "currentChildNode");
			return (Criteria) this;
		}

		public Criteria andCurrentChildNodeGreaterThanOrEqualTo(Integer value) {
			addCriterion("CURRENT_CHILD_NODE >=", value, "currentChildNode");
			return (Criteria) this;
		}

		public Criteria andCurrentChildNodeLessThan(Integer value) {
			addCriterion("CURRENT_CHILD_NODE <", value, "currentChildNode");
			return (Criteria) this;
		}

		public Criteria andCurrentChildNodeLessThanOrEqualTo(Integer value) {
			addCriterion("CURRENT_CHILD_NODE <=", value, "currentChildNode");
			return (Criteria) this;
		}

		public Criteria andCurrentChildNodeIn(List<Integer> values) {
			addCriterion("CURRENT_CHILD_NODE in", values, "currentChildNode");
			return (Criteria) this;
		}

		public Criteria andCurrentChildNodeNotIn(List<Integer> values) {
			addCriterion("CURRENT_CHILD_NODE not in", values,
					"currentChildNode");
			return (Criteria) this;
		}

		public Criteria andCurrentChildNodeBetween(Integer value1,
				Integer value2) {
			addCriterion("CURRENT_CHILD_NODE between", value1, value2,
					"currentChildNode");
			return (Criteria) this;
		}

		public Criteria andCurrentChildNodeNotBetween(Integer value1,
				Integer value2) {
			addCriterion("CURRENT_CHILD_NODE not between", value1, value2,
					"currentChildNode");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andSourceOrgIdIsNull() {
			addCriterion("SOURCE_ORG_ID is null");
			return (Criteria) this;
		}

		public Criteria andSourceOrgIdIsNotNull() {
			addCriterion("SOURCE_ORG_ID is not null");
			return (Criteria) this;
		}

		public Criteria andSourceOrgIdEqualTo(String value) {
			addCriterion("SOURCE_ORG_ID =", value, "sourceOrgId");
			return (Criteria) this;
		}

		public Criteria andSourceOrgIdNotEqualTo(String value) {
			addCriterion("SOURCE_ORG_ID <>", value, "sourceOrgId");
			return (Criteria) this;
		}

		public Criteria andSourceOrgIdGreaterThan(String value) {
			addCriterion("SOURCE_ORG_ID >", value, "sourceOrgId");
			return (Criteria) this;
		}

		public Criteria andSourceOrgIdGreaterThanOrEqualTo(String value) {
			addCriterion("SOURCE_ORG_ID >=", value, "sourceOrgId");
			return (Criteria) this;
		}

		public Criteria andSourceOrgIdLessThan(String value) {
			addCriterion("SOURCE_ORG_ID <", value, "sourceOrgId");
			return (Criteria) this;
		}

		public Criteria andSourceOrgIdLessThanOrEqualTo(String value) {
			addCriterion("SOURCE_ORG_ID <=", value, "sourceOrgId");
			return (Criteria) this;
		}

		public Criteria andSourceOrgIdLike(String value) {
			addCriterion("SOURCE_ORG_ID like", value, "sourceOrgId");
			return (Criteria) this;
		}

		public Criteria andSourceOrgIdNotLike(String value) {
			addCriterion("SOURCE_ORG_ID not like", value, "sourceOrgId");
			return (Criteria) this;
		}

		public Criteria andSourceOrgIdIn(List<String> values) {
			addCriterion("SOURCE_ORG_ID in", values, "sourceOrgId");
			return (Criteria) this;
		}

		public Criteria andSourceOrgIdNotIn(List<String> values) {
			addCriterion("SOURCE_ORG_ID not in", values, "sourceOrgId");
			return (Criteria) this;
		}

		public Criteria andSourceOrgIdBetween(String value1, String value2) {
			addCriterion("SOURCE_ORG_ID between", value1, value2, "sourceOrgId");
			return (Criteria) this;
		}

		public Criteria andSourceOrgIdNotBetween(String value1, String value2) {
			addCriterion("SOURCE_ORG_ID not between", value1, value2,
					"sourceOrgId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIsNull() {
			addCriterion("CREATER_ID is null");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIsNotNull() {
			addCriterion("CREATER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCreaterIdEqualTo(String value) {
			addCriterion("CREATER_ID =", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotEqualTo(String value) {
			addCriterion("CREATER_ID <>", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdGreaterThan(String value) {
			addCriterion("CREATER_ID >", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdGreaterThanOrEqualTo(String value) {
			addCriterion("CREATER_ID >=", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLessThan(String value) {
			addCriterion("CREATER_ID <", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLessThanOrEqualTo(String value) {
			addCriterion("CREATER_ID <=", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLike(String value) {
			addCriterion("CREATER_ID like", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotLike(String value) {
			addCriterion("CREATER_ID not like", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIn(List<String> values) {
			addCriterion("CREATER_ID in", values, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotIn(List<String> values) {
			addCriterion("CREATER_ID not in", values, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdBetween(String value1, String value2) {
			addCriterion("CREATER_ID between", value1, value2, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotBetween(String value1, String value2) {
			addCriterion("CREATER_ID not between", value1, value2, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("UPDATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("UPDATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("UPDATE_TIME =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("UPDATE_TIME <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("UPDATE_TIME >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("UPDATE_TIME <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("UPDATE_TIME in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("UPDATE_TIME not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeIsNull() {
			addCriterion("REGISTER_TIME is null");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeIsNotNull() {
			addCriterion("REGISTER_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeEqualTo(Date value) {
			addCriterion("REGISTER_TIME =", value, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeNotEqualTo(Date value) {
			addCriterion("REGISTER_TIME <>", value, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeGreaterThan(Date value) {
			addCriterion("REGISTER_TIME >", value, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("REGISTER_TIME >=", value, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeLessThan(Date value) {
			addCriterion("REGISTER_TIME <", value, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeLessThanOrEqualTo(Date value) {
			addCriterion("REGISTER_TIME <=", value, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeIn(List<Date> values) {
			addCriterion("REGISTER_TIME in", values, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeNotIn(List<Date> values) {
			addCriterion("REGISTER_TIME not in", values, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeBetween(Date value1, Date value2) {
			addCriterion("REGISTER_TIME between", value1, value2,
					"registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeNotBetween(Date value1, Date value2) {
			addCriterion("REGISTER_TIME not between", value1, value2,
					"registerTime");
			return (Criteria) this;
		}

		public Criteria andUpdateIdIsNull() {
			addCriterion("UPDATE_ID is null");
			return (Criteria) this;
		}

		public Criteria andUpdateIdIsNotNull() {
			addCriterion("UPDATE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateIdEqualTo(String value) {
			addCriterion("UPDATE_ID =", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotEqualTo(String value) {
			addCriterion("UPDATE_ID <>", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdGreaterThan(String value) {
			addCriterion("UPDATE_ID >", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_ID >=", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdLessThan(String value) {
			addCriterion("UPDATE_ID <", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_ID <=", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdLike(String value) {
			addCriterion("UPDATE_ID like", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotLike(String value) {
			addCriterion("UPDATE_ID not like", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdIn(List<String> values) {
			addCriterion("UPDATE_ID in", values, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotIn(List<String> values) {
			addCriterion("UPDATE_ID not in", values, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdBetween(String value1, String value2) {
			addCriterion("UPDATE_ID between", value1, value2, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotBetween(String value1, String value2) {
			addCriterion("UPDATE_ID not between", value1, value2, "updateId");
			return (Criteria) this;
		}

		public Criteria andAcceptTimeIsNull() {
			addCriterion("ACCEPT_TIME is null");
			return (Criteria) this;
		}

		public Criteria andAcceptTimeIsNotNull() {
			addCriterion("ACCEPT_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andAcceptTimeEqualTo(Date value) {
			addCriterion("ACCEPT_TIME =", value, "acceptTime");
			return (Criteria) this;
		}

		public Criteria andAcceptTimeNotEqualTo(Date value) {
			addCriterion("ACCEPT_TIME <>", value, "acceptTime");
			return (Criteria) this;
		}

		public Criteria andAcceptTimeGreaterThan(Date value) {
			addCriterion("ACCEPT_TIME >", value, "acceptTime");
			return (Criteria) this;
		}

		public Criteria andAcceptTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("ACCEPT_TIME >=", value, "acceptTime");
			return (Criteria) this;
		}

		public Criteria andAcceptTimeLessThan(Date value) {
			addCriterion("ACCEPT_TIME <", value, "acceptTime");
			return (Criteria) this;
		}

		public Criteria andAcceptTimeLessThanOrEqualTo(Date value) {
			addCriterion("ACCEPT_TIME <=", value, "acceptTime");
			return (Criteria) this;
		}

		public Criteria andAcceptTimeIn(List<Date> values) {
			addCriterion("ACCEPT_TIME in", values, "acceptTime");
			return (Criteria) this;
		}

		public Criteria andAcceptTimeNotIn(List<Date> values) {
			addCriterion("ACCEPT_TIME not in", values, "acceptTime");
			return (Criteria) this;
		}

		public Criteria andAcceptTimeBetween(Date value1, Date value2) {
			addCriterion("ACCEPT_TIME between", value1, value2, "acceptTime");
			return (Criteria) this;
		}

		public Criteria andAcceptTimeNotBetween(Date value1, Date value2) {
			addCriterion("ACCEPT_TIME not between", value1, value2,
					"acceptTime");
			return (Criteria) this;
		}

		public Criteria andCurrentOwnerIsNull() {
			addCriterion("CURRENT_OWNER is null");
			return (Criteria) this;
		}

		public Criteria andCurrentOwnerIsNotNull() {
			addCriterion("CURRENT_OWNER is not null");
			return (Criteria) this;
		}

		public Criteria andCurrentOwnerEqualTo(String value) {
			addCriterion("CURRENT_OWNER =", value, "currentOwner");
			return (Criteria) this;
		}

		public Criteria andCurrentOwnerNotEqualTo(String value) {
			addCriterion("CURRENT_OWNER <>", value, "currentOwner");
			return (Criteria) this;
		}

		public Criteria andCurrentOwnerGreaterThan(String value) {
			addCriterion("CURRENT_OWNER >", value, "currentOwner");
			return (Criteria) this;
		}

		public Criteria andCurrentOwnerGreaterThanOrEqualTo(String value) {
			addCriterion("CURRENT_OWNER >=", value, "currentOwner");
			return (Criteria) this;
		}

		public Criteria andCurrentOwnerLessThan(String value) {
			addCriterion("CURRENT_OWNER <", value, "currentOwner");
			return (Criteria) this;
		}

		public Criteria andCurrentOwnerLessThanOrEqualTo(String value) {
			addCriterion("CURRENT_OWNER <=", value, "currentOwner");
			return (Criteria) this;
		}

		public Criteria andCurrentOwnerLike(String value) {
			addCriterion("CURRENT_OWNER like", value, "currentOwner");
			return (Criteria) this;
		}

		public Criteria andCurrentOwnerNotLike(String value) {
			addCriterion("CURRENT_OWNER not like", value, "currentOwner");
			return (Criteria) this;
		}

		public Criteria andCurrentOwnerIn(List<String> values) {
			addCriterion("CURRENT_OWNER in", values, "currentOwner");
			return (Criteria) this;
		}

		public Criteria andCurrentOwnerNotIn(List<String> values) {
			addCriterion("CURRENT_OWNER not in", values, "currentOwner");
			return (Criteria) this;
		}

		public Criteria andCurrentOwnerBetween(String value1, String value2) {
			addCriterion("CURRENT_OWNER between", value1, value2,
					"currentOwner");
			return (Criteria) this;
		}

		public Criteria andCurrentOwnerNotBetween(String value1, String value2) {
			addCriterion("CURRENT_OWNER not between", value1, value2,
					"currentOwner");
			return (Criteria) this;
		}

		public Criteria andCompleteTimeIsNull() {
			addCriterion("COMPLETE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCompleteTimeIsNotNull() {
			addCriterion("COMPLETE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCompleteTimeEqualTo(Date value) {
			addCriterion("COMPLETE_TIME =", value, "completeTime");
			return (Criteria) this;
		}

		public Criteria andCompleteTimeNotEqualTo(Date value) {
			addCriterion("COMPLETE_TIME <>", value, "completeTime");
			return (Criteria) this;
		}

		public Criteria andCompleteTimeGreaterThan(Date value) {
			addCriterion("COMPLETE_TIME >", value, "completeTime");
			return (Criteria) this;
		}

		public Criteria andCompleteTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("COMPLETE_TIME >=", value, "completeTime");
			return (Criteria) this;
		}

		public Criteria andCompleteTimeLessThan(Date value) {
			addCriterion("COMPLETE_TIME <", value, "completeTime");
			return (Criteria) this;
		}

		public Criteria andCompleteTimeLessThanOrEqualTo(Date value) {
			addCriterion("COMPLETE_TIME <=", value, "completeTime");
			return (Criteria) this;
		}

		public Criteria andCompleteTimeIn(List<Date> values) {
			addCriterion("COMPLETE_TIME in", values, "completeTime");
			return (Criteria) this;
		}

		public Criteria andCompleteTimeNotIn(List<Date> values) {
			addCriterion("COMPLETE_TIME not in", values, "completeTime");
			return (Criteria) this;
		}

		public Criteria andCompleteTimeBetween(Date value1, Date value2) {
			addCriterion("COMPLETE_TIME between", value1, value2,
					"completeTime");
			return (Criteria) this;
		}

		public Criteria andCompleteTimeNotBetween(Date value1, Date value2) {
			addCriterion("COMPLETE_TIME not between", value1, value2,
					"completeTime");
			return (Criteria) this;
		}

		public Criteria andApplyTypeIsNull() {
			addCriterion("APPLY_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andApplyTypeIsNotNull() {
			addCriterion("APPLY_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andApplyTypeEqualTo(String value) {
			addCriterion("APPLY_TYPE =", value, "applyType");
			return (Criteria) this;
		}

		public Criteria andApplyTypeNotEqualTo(String value) {
			addCriterion("APPLY_TYPE <>", value, "applyType");
			return (Criteria) this;
		}

		public Criteria andApplyTypeGreaterThan(String value) {
			addCriterion("APPLY_TYPE >", value, "applyType");
			return (Criteria) this;
		}

		public Criteria andApplyTypeGreaterThanOrEqualTo(String value) {
			addCriterion("APPLY_TYPE >=", value, "applyType");
			return (Criteria) this;
		}

		public Criteria andApplyTypeLessThan(String value) {
			addCriterion("APPLY_TYPE <", value, "applyType");
			return (Criteria) this;
		}

		public Criteria andApplyTypeLessThanOrEqualTo(String value) {
			addCriterion("APPLY_TYPE <=", value, "applyType");
			return (Criteria) this;
		}

		public Criteria andApplyTypeLike(String value) {
			addCriterion("APPLY_TYPE like", value, "applyType");
			return (Criteria) this;
		}

		public Criteria andApplyTypeNotLike(String value) {
			addCriterion("APPLY_TYPE not like", value, "applyType");
			return (Criteria) this;
		}

		public Criteria andApplyTypeIn(List<String> values) {
			addCriterion("APPLY_TYPE in", values, "applyType");
			return (Criteria) this;
		}

		public Criteria andApplyTypeNotIn(List<String> values) {
			addCriterion("APPLY_TYPE not in", values, "applyType");
			return (Criteria) this;
		}

		public Criteria andApplyTypeBetween(String value1, String value2) {
			addCriterion("APPLY_TYPE between", value1, value2, "applyType");
			return (Criteria) this;
		}

		public Criteria andApplyTypeNotBetween(String value1, String value2) {
			addCriterion("APPLY_TYPE not between", value1, value2, "applyType");
			return (Criteria) this;
		}

		public Criteria andCaseAcceptanceTimeIsNull() {
			addCriterion("CASE_ACCEPTANCE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCaseAcceptanceTimeIsNotNull() {
			addCriterion("CASE_ACCEPTANCE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCaseAcceptanceTimeEqualTo(Date value) {
			addCriterion("CASE_ACCEPTANCE_TIME =", value, "caseAcceptanceTime");
			return (Criteria) this;
		}

		public Criteria andCaseAcceptanceTimeNotEqualTo(Date value) {
			addCriterion("CASE_ACCEPTANCE_TIME <>", value, "caseAcceptanceTime");
			return (Criteria) this;
		}

		public Criteria andCaseAcceptanceTimeGreaterThan(Date value) {
			addCriterion("CASE_ACCEPTANCE_TIME >", value, "caseAcceptanceTime");
			return (Criteria) this;
		}

		public Criteria andCaseAcceptanceTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CASE_ACCEPTANCE_TIME >=", value, "caseAcceptanceTime");
			return (Criteria) this;
		}

		public Criteria andCaseAcceptanceTimeLessThan(Date value) {
			addCriterion("CASE_ACCEPTANCE_TIME <", value, "caseAcceptanceTime");
			return (Criteria) this;
		}

		public Criteria andCaseAcceptanceTimeLessThanOrEqualTo(Date value) {
			addCriterion("CASE_ACCEPTANCE_TIME <=", value, "caseAcceptanceTime");
			return (Criteria) this;
		}

		public Criteria andCaseAcceptanceTimeIn(List<Date> values) {
			addCriterion("CASE_ACCEPTANCE_TIME in", values,
					"caseAcceptanceTime");
			return (Criteria) this;
		}

		public Criteria andCaseAcceptanceTimeNotIn(List<Date> values) {
			addCriterion("CASE_ACCEPTANCE_TIME not in", values,
					"caseAcceptanceTime");
			return (Criteria) this;
		}

		public Criteria andCaseAcceptanceTimeBetween(Date value1, Date value2) {
			addCriterion("CASE_ACCEPTANCE_TIME between", value1, value2,
					"caseAcceptanceTime");
			return (Criteria) this;
		}

		public Criteria andCaseAcceptanceTimeNotBetween(Date value1, Date value2) {
			addCriterion("CASE_ACCEPTANCE_TIME not between", value1, value2,
					"caseAcceptanceTime");
			return (Criteria) this;
		}

		public Criteria andSignAbriProtocolModeIsNull() {
			addCriterion("SIGN_ABRI_PROTOCOL_MODE is null");
			return (Criteria) this;
		}

		public Criteria andSignAbriProtocolModeIsNotNull() {
			addCriterion("SIGN_ABRI_PROTOCOL_MODE is not null");
			return (Criteria) this;
		}

		public Criteria andSignAbriProtocolModeEqualTo(String value) {
			addCriterion("SIGN_ABRI_PROTOCOL_MODE =", value,
					"signAbriProtocolMode");
			return (Criteria) this;
		}

		public Criteria andSignAbriProtocolModeNotEqualTo(String value) {
			addCriterion("SIGN_ABRI_PROTOCOL_MODE <>", value,
					"signAbriProtocolMode");
			return (Criteria) this;
		}

		public Criteria andSignAbriProtocolModeGreaterThan(String value) {
			addCriterion("SIGN_ABRI_PROTOCOL_MODE >", value,
					"signAbriProtocolMode");
			return (Criteria) this;
		}

		public Criteria andSignAbriProtocolModeGreaterThanOrEqualTo(String value) {
			addCriterion("SIGN_ABRI_PROTOCOL_MODE >=", value,
					"signAbriProtocolMode");
			return (Criteria) this;
		}

		public Criteria andSignAbriProtocolModeLessThan(String value) {
			addCriterion("SIGN_ABRI_PROTOCOL_MODE <", value,
					"signAbriProtocolMode");
			return (Criteria) this;
		}

		public Criteria andSignAbriProtocolModeLessThanOrEqualTo(String value) {
			addCriterion("SIGN_ABRI_PROTOCOL_MODE <=", value,
					"signAbriProtocolMode");
			return (Criteria) this;
		}

		public Criteria andSignAbriProtocolModeLike(String value) {
			addCriterion("SIGN_ABRI_PROTOCOL_MODE like", value,
					"signAbriProtocolMode");
			return (Criteria) this;
		}

		public Criteria andSignAbriProtocolModeNotLike(String value) {
			addCriterion("SIGN_ABRI_PROTOCOL_MODE not like", value,
					"signAbriProtocolMode");
			return (Criteria) this;
		}

		public Criteria andSignAbriProtocolModeIn(List<String> values) {
			addCriterion("SIGN_ABRI_PROTOCOL_MODE in", values,
					"signAbriProtocolMode");
			return (Criteria) this;
		}

		public Criteria andSignAbriProtocolModeNotIn(List<String> values) {
			addCriterion("SIGN_ABRI_PROTOCOL_MODE not in", values,
					"signAbriProtocolMode");
			return (Criteria) this;
		}

		public Criteria andSignAbriProtocolModeBetween(String value1,
				String value2) {
			addCriterion("SIGN_ABRI_PROTOCOL_MODE between", value1, value2,
					"signAbriProtocolMode");
			return (Criteria) this;
		}

		public Criteria andSignAbriProtocolModeNotBetween(String value1,
				String value2) {
			addCriterion("SIGN_ABRI_PROTOCOL_MODE not between", value1, value2,
					"signAbriProtocolMode");
			return (Criteria) this;
		}

		public Criteria andSignTimeIsNull() {
			addCriterion("SIGN_TIME is null");
			return (Criteria) this;
		}

		public Criteria andSignTimeIsNotNull() {
			addCriterion("SIGN_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andSignTimeEqualTo(Date value) {
			addCriterion("SIGN_TIME =", value, "signTime");
			return (Criteria) this;
		}

		public Criteria andSignTimeNotEqualTo(Date value) {
			addCriterion("SIGN_TIME <>", value, "signTime");
			return (Criteria) this;
		}

		public Criteria andSignTimeGreaterThan(Date value) {
			addCriterion("SIGN_TIME >", value, "signTime");
			return (Criteria) this;
		}

		public Criteria andSignTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("SIGN_TIME >=", value, "signTime");
			return (Criteria) this;
		}

		public Criteria andSignTimeLessThan(Date value) {
			addCriterion("SIGN_TIME <", value, "signTime");
			return (Criteria) this;
		}

		public Criteria andSignTimeLessThanOrEqualTo(Date value) {
			addCriterion("SIGN_TIME <=", value, "signTime");
			return (Criteria) this;
		}

		public Criteria andSignTimeIn(List<Date> values) {
			addCriterion("SIGN_TIME in", values, "signTime");
			return (Criteria) this;
		}

		public Criteria andSignTimeNotIn(List<Date> values) {
			addCriterion("SIGN_TIME not in", values, "signTime");
			return (Criteria) this;
		}

		public Criteria andSignTimeBetween(Date value1, Date value2) {
			addCriterion("SIGN_TIME between", value1, value2, "signTime");
			return (Criteria) this;
		}

		public Criteria andSignTimeNotBetween(Date value1, Date value2) {
			addCriterion("SIGN_TIME not between", value1, value2, "signTime");
			return (Criteria) this;
		}

		public Criteria andProtocolNameIsNull() {
			addCriterion("PROTOCOL_NAME is null");
			return (Criteria) this;
		}

		public Criteria andProtocolNameIsNotNull() {
			addCriterion("PROTOCOL_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andProtocolNameEqualTo(String value) {
			addCriterion("PROTOCOL_NAME =", value, "protocolName");
			return (Criteria) this;
		}

		public Criteria andProtocolNameNotEqualTo(String value) {
			addCriterion("PROTOCOL_NAME <>", value, "protocolName");
			return (Criteria) this;
		}

		public Criteria andProtocolNameGreaterThan(String value) {
			addCriterion("PROTOCOL_NAME >", value, "protocolName");
			return (Criteria) this;
		}

		public Criteria andProtocolNameGreaterThanOrEqualTo(String value) {
			addCriterion("PROTOCOL_NAME >=", value, "protocolName");
			return (Criteria) this;
		}

		public Criteria andProtocolNameLessThan(String value) {
			addCriterion("PROTOCOL_NAME <", value, "protocolName");
			return (Criteria) this;
		}

		public Criteria andProtocolNameLessThanOrEqualTo(String value) {
			addCriterion("PROTOCOL_NAME <=", value, "protocolName");
			return (Criteria) this;
		}

		public Criteria andProtocolNameLike(String value) {
			addCriterion("PROTOCOL_NAME like", value, "protocolName");
			return (Criteria) this;
		}

		public Criteria andProtocolNameNotLike(String value) {
			addCriterion("PROTOCOL_NAME not like", value, "protocolName");
			return (Criteria) this;
		}

		public Criteria andProtocolNameIn(List<String> values) {
			addCriterion("PROTOCOL_NAME in", values, "protocolName");
			return (Criteria) this;
		}

		public Criteria andProtocolNameNotIn(List<String> values) {
			addCriterion("PROTOCOL_NAME not in", values, "protocolName");
			return (Criteria) this;
		}

		public Criteria andProtocolNameBetween(String value1, String value2) {
			addCriterion("PROTOCOL_NAME between", value1, value2,
					"protocolName");
			return (Criteria) this;
		}

		public Criteria andProtocolNameNotBetween(String value1, String value2) {
			addCriterion("PROTOCOL_NAME not between", value1, value2,
					"protocolName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table case_info
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * case_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}