package com.zyxy.common.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CaseAvoidRecordExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	public CaseAvoidRecordExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCaseIdIsNull() {
			addCriterion("CASE_ID is null");
			return (Criteria) this;
		}

		public Criteria andCaseIdIsNotNull() {
			addCriterion("CASE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCaseIdEqualTo(String value) {
			addCriterion("CASE_ID =", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotEqualTo(String value) {
			addCriterion("CASE_ID <>", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdGreaterThan(String value) {
			addCriterion("CASE_ID >", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdGreaterThanOrEqualTo(String value) {
			addCriterion("CASE_ID >=", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLessThan(String value) {
			addCriterion("CASE_ID <", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLessThanOrEqualTo(String value) {
			addCriterion("CASE_ID <=", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLike(String value) {
			addCriterion("CASE_ID like", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotLike(String value) {
			addCriterion("CASE_ID not like", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdIn(List<String> values) {
			addCriterion("CASE_ID in", values, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotIn(List<String> values) {
			addCriterion("CASE_ID not in", values, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdBetween(String value1, String value2) {
			addCriterion("CASE_ID between", value1, value2, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotBetween(String value1, String value2) {
			addCriterion("CASE_ID not between", value1, value2, "caseId");
			return (Criteria) this;
		}

		public Criteria andAvoidIdIsNull() {
			addCriterion("AVOID_ID is null");
			return (Criteria) this;
		}

		public Criteria andAvoidIdIsNotNull() {
			addCriterion("AVOID_ID is not null");
			return (Criteria) this;
		}

		public Criteria andAvoidIdEqualTo(String value) {
			addCriterion("AVOID_ID =", value, "avoidId");
			return (Criteria) this;
		}

		public Criteria andAvoidIdNotEqualTo(String value) {
			addCriterion("AVOID_ID <>", value, "avoidId");
			return (Criteria) this;
		}

		public Criteria andAvoidIdGreaterThan(String value) {
			addCriterion("AVOID_ID >", value, "avoidId");
			return (Criteria) this;
		}

		public Criteria andAvoidIdGreaterThanOrEqualTo(String value) {
			addCriterion("AVOID_ID >=", value, "avoidId");
			return (Criteria) this;
		}

		public Criteria andAvoidIdLessThan(String value) {
			addCriterion("AVOID_ID <", value, "avoidId");
			return (Criteria) this;
		}

		public Criteria andAvoidIdLessThanOrEqualTo(String value) {
			addCriterion("AVOID_ID <=", value, "avoidId");
			return (Criteria) this;
		}

		public Criteria andAvoidIdLike(String value) {
			addCriterion("AVOID_ID like", value, "avoidId");
			return (Criteria) this;
		}

		public Criteria andAvoidIdNotLike(String value) {
			addCriterion("AVOID_ID not like", value, "avoidId");
			return (Criteria) this;
		}

		public Criteria andAvoidIdIn(List<String> values) {
			addCriterion("AVOID_ID in", values, "avoidId");
			return (Criteria) this;
		}

		public Criteria andAvoidIdNotIn(List<String> values) {
			addCriterion("AVOID_ID not in", values, "avoidId");
			return (Criteria) this;
		}

		public Criteria andAvoidIdBetween(String value1, String value2) {
			addCriterion("AVOID_ID between", value1, value2, "avoidId");
			return (Criteria) this;
		}

		public Criteria andAvoidIdNotBetween(String value1, String value2) {
			addCriterion("AVOID_ID not between", value1, value2, "avoidId");
			return (Criteria) this;
		}

		public Criteria andAvoidTypeIsNull() {
			addCriterion("AVOID_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andAvoidTypeIsNotNull() {
			addCriterion("AVOID_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andAvoidTypeEqualTo(String value) {
			addCriterion("AVOID_TYPE =", value, "avoidType");
			return (Criteria) this;
		}

		public Criteria andAvoidTypeNotEqualTo(String value) {
			addCriterion("AVOID_TYPE <>", value, "avoidType");
			return (Criteria) this;
		}

		public Criteria andAvoidTypeGreaterThan(String value) {
			addCriterion("AVOID_TYPE >", value, "avoidType");
			return (Criteria) this;
		}

		public Criteria andAvoidTypeGreaterThanOrEqualTo(String value) {
			addCriterion("AVOID_TYPE >=", value, "avoidType");
			return (Criteria) this;
		}

		public Criteria andAvoidTypeLessThan(String value) {
			addCriterion("AVOID_TYPE <", value, "avoidType");
			return (Criteria) this;
		}

		public Criteria andAvoidTypeLessThanOrEqualTo(String value) {
			addCriterion("AVOID_TYPE <=", value, "avoidType");
			return (Criteria) this;
		}

		public Criteria andAvoidTypeLike(String value) {
			addCriterion("AVOID_TYPE like", value, "avoidType");
			return (Criteria) this;
		}

		public Criteria andAvoidTypeNotLike(String value) {
			addCriterion("AVOID_TYPE not like", value, "avoidType");
			return (Criteria) this;
		}

		public Criteria andAvoidTypeIn(List<String> values) {
			addCriterion("AVOID_TYPE in", values, "avoidType");
			return (Criteria) this;
		}

		public Criteria andAvoidTypeNotIn(List<String> values) {
			addCriterion("AVOID_TYPE not in", values, "avoidType");
			return (Criteria) this;
		}

		public Criteria andAvoidTypeBetween(String value1, String value2) {
			addCriterion("AVOID_TYPE between", value1, value2, "avoidType");
			return (Criteria) this;
		}

		public Criteria andAvoidTypeNotBetween(String value1, String value2) {
			addCriterion("AVOID_TYPE not between", value1, value2, "avoidType");
			return (Criteria) this;
		}

		public Criteria andAvoidStyleIsNull() {
			addCriterion("AVOID_STYLE is null");
			return (Criteria) this;
		}

		public Criteria andAvoidStyleIsNotNull() {
			addCriterion("AVOID_STYLE is not null");
			return (Criteria) this;
		}

		public Criteria andAvoidStyleEqualTo(String value) {
			addCriterion("AVOID_STYLE =", value, "avoidStyle");
			return (Criteria) this;
		}

		public Criteria andAvoidStyleNotEqualTo(String value) {
			addCriterion("AVOID_STYLE <>", value, "avoidStyle");
			return (Criteria) this;
		}

		public Criteria andAvoidStyleGreaterThan(String value) {
			addCriterion("AVOID_STYLE >", value, "avoidStyle");
			return (Criteria) this;
		}

		public Criteria andAvoidStyleGreaterThanOrEqualTo(String value) {
			addCriterion("AVOID_STYLE >=", value, "avoidStyle");
			return (Criteria) this;
		}

		public Criteria andAvoidStyleLessThan(String value) {
			addCriterion("AVOID_STYLE <", value, "avoidStyle");
			return (Criteria) this;
		}

		public Criteria andAvoidStyleLessThanOrEqualTo(String value) {
			addCriterion("AVOID_STYLE <=", value, "avoidStyle");
			return (Criteria) this;
		}

		public Criteria andAvoidStyleLike(String value) {
			addCriterion("AVOID_STYLE like", value, "avoidStyle");
			return (Criteria) this;
		}

		public Criteria andAvoidStyleNotLike(String value) {
			addCriterion("AVOID_STYLE not like", value, "avoidStyle");
			return (Criteria) this;
		}

		public Criteria andAvoidStyleIn(List<String> values) {
			addCriterion("AVOID_STYLE in", values, "avoidStyle");
			return (Criteria) this;
		}

		public Criteria andAvoidStyleNotIn(List<String> values) {
			addCriterion("AVOID_STYLE not in", values, "avoidStyle");
			return (Criteria) this;
		}

		public Criteria andAvoidStyleBetween(String value1, String value2) {
			addCriterion("AVOID_STYLE between", value1, value2, "avoidStyle");
			return (Criteria) this;
		}

		public Criteria andAvoidStyleNotBetween(String value1, String value2) {
			addCriterion("AVOID_STYLE not between", value1, value2,
					"avoidStyle");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIsNull() {
			addCriterion("CREATER_ID is null");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIsNotNull() {
			addCriterion("CREATER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCreaterIdEqualTo(String value) {
			addCriterion("CREATER_ID =", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotEqualTo(String value) {
			addCriterion("CREATER_ID <>", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdGreaterThan(String value) {
			addCriterion("CREATER_ID >", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdGreaterThanOrEqualTo(String value) {
			addCriterion("CREATER_ID >=", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLessThan(String value) {
			addCriterion("CREATER_ID <", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLessThanOrEqualTo(String value) {
			addCriterion("CREATER_ID <=", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLike(String value) {
			addCriterion("CREATER_ID like", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotLike(String value) {
			addCriterion("CREATER_ID not like", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIn(List<String> values) {
			addCriterion("CREATER_ID in", values, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotIn(List<String> values) {
			addCriterion("CREATER_ID not in", values, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdBetween(String value1, String value2) {
			addCriterion("CREATER_ID between", value1, value2, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotBetween(String value1, String value2) {
			addCriterion("CREATER_ID not between", value1, value2, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table case_avoid_record
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}