package com.zyxy.common.domain;

import java.io.Serializable;

public class CaseJurisDisProcessRecord implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_juris_dis_process_record.ID
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_juris_dis_process_record.CASE_ID
	 * @mbggenerated
	 */
	private String caseId;
	/**
	 * Database Column Remarks: 状态，0- 等待仲裁员出具管辖权异议决定书(审核中也是这个状态)，1- 完成 This field was generated by MyBatis Generator. This field corresponds to the database column case_juris_dis_process_record.STATUS
	 * @mbggenerated
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_juris_dis_process_record.REQUEST_TYPE
	 * @mbggenerated
	 */
	private String requestType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_juris_dis_process_record
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_juris_dis_process_record.ID
	 * @return  the value of case_juris_dis_process_record.ID
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_juris_dis_process_record.ID
	 * @param id  the value for case_juris_dis_process_record.ID
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_juris_dis_process_record.CASE_ID
	 * @return  the value of case_juris_dis_process_record.CASE_ID
	 * @mbggenerated
	 */
	public String getCaseId() {
		return caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_juris_dis_process_record.CASE_ID
	 * @param caseId  the value for case_juris_dis_process_record.CASE_ID
	 * @mbggenerated
	 */
	public void setCaseId(String caseId) {
		this.caseId = caseId == null ? null : caseId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_juris_dis_process_record.STATUS
	 * @return  the value of case_juris_dis_process_record.STATUS
	 * @mbggenerated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_juris_dis_process_record.STATUS
	 * @param status  the value for case_juris_dis_process_record.STATUS
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_juris_dis_process_record.REQUEST_TYPE
	 * @return  the value of case_juris_dis_process_record.REQUEST_TYPE
	 * @mbggenerated
	 */
	public String getRequestType() {
		return requestType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_juris_dis_process_record.REQUEST_TYPE
	 * @param requestType  the value for case_juris_dis_process_record.REQUEST_TYPE
	 * @mbggenerated
	 */
	public void setRequestType(String requestType) {
		this.requestType = requestType == null ? null : requestType.trim();
	}
}