package com.zyxy.common.domain;

import java.io.Serializable;
import java.util.Date;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * @author tanquan
 *
 * case_approve
 *
 * @mbggenerated do_not_delete_during_merge
 */
@ApiModel(value ="CaseApprove")
public class CaseApprove implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_approve.ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "审批id")
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_approve.CASE_ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "案件ID")
	private String caseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_approve.REQUEST_ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "请求ID")
	private String requestId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_approve.APPROVE_TYPE
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "审批类型 ")
	private String approveType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_approve.APPROVE_STATUS
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "0-待审核，1-审核通过，2-审核未通过")
	private String approveStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_approve.CREATE_TIME
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "")
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_approve.BUSI_ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "业务id")
	private String busiId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_approve.CREATER_ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "创建人id")
	private String createrId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_approve.APPROVE_USER_ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "当前审批人")
	private String approveUserId;

	/**
	 * 组庭标志
	 * 0-未组庭
	 * 1-已组庭
	 */
	@ApiModelProperty(value = "组庭标志,0-未组庭,1-已组庭")
	private String tribunalMark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_approve
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_approve.ID
	 * @return  the value of case_approve.ID
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_approve.ID
	 * @param id  the value for case_approve.ID
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_approve.CASE_ID
	 * @return  the value of case_approve.CASE_ID
	 * @mbggenerated
	 */
	public String getCaseId() {
		return caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_approve.CASE_ID
	 * @param caseId  the value for case_approve.CASE_ID
	 * @mbggenerated
	 */
	public void setCaseId(String caseId) {
		this.caseId = caseId == null ? null : caseId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_approve.REQUEST_ID
	 * @return  the value of case_approve.REQUEST_ID
	 * @mbggenerated
	 */
	public String getRequestId() {
		return requestId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_approve.REQUEST_ID
	 * @param requestId  the value for case_approve.REQUEST_ID
	 * @mbggenerated
	 */
	public void setRequestId(String requestId) {
		this.requestId = requestId == null ? null : requestId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_approve.APPROVE_TYPE
	 * @return  the value of case_approve.APPROVE_TYPE
	 * @mbggenerated
	 */
	public String getApproveType() {
		return approveType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_approve.APPROVE_TYPE
	 * @param approveType  the value for case_approve.APPROVE_TYPE
	 * @mbggenerated
	 */
	public void setApproveType(String approveType) {
		this.approveType = approveType == null ? null : approveType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_approve.APPROVE_STATUS
	 * @return  the value of case_approve.APPROVE_STATUS
	 * @mbggenerated
	 */
	public String getApproveStatus() {
		return approveStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_approve.APPROVE_STATUS
	 * @param approveStatus  the value for case_approve.APPROVE_STATUS
	 * @mbggenerated
	 */
	public void setApproveStatus(String approveStatus) {
		this.approveStatus = approveStatus == null ? null : approveStatus
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_approve.CREATE_TIME
	 * @return  the value of case_approve.CREATE_TIME
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_approve.CREATE_TIME
	 * @param createTime  the value for case_approve.CREATE_TIME
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_approve.BUSI_ID
	 * @return  the value of case_approve.BUSI_ID
	 * @mbggenerated
	 */
	public String getBusiId() {
		return busiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_approve.BUSI_ID
	 * @param busiId  the value for case_approve.BUSI_ID
	 * @mbggenerated
	 */
	public void setBusiId(String busiId) {
		this.busiId = busiId == null ? null : busiId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_approve.CREATER_ID
	 * @return  the value of case_approve.CREATER_ID
	 * @mbggenerated
	 */
	public String getCreaterId() {
		return createrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_approve.CREATER_ID
	 * @param createrId  the value for case_approve.CREATER_ID
	 * @mbggenerated
	 */
	public void setCreaterId(String createrId) {
		this.createrId = createrId == null ? null : createrId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_approve.APPROVE_USER_ID
	 * @return  the value of case_approve.APPROVE_USER_ID
	 * @mbggenerated
	 */
	public String getApproveUserId() {
		return approveUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_approve.APPROVE_USER_ID
	 * @param approveUserId  the value for case_approve.APPROVE_USER_ID
	 * @mbggenerated
	 */
	public void setApproveUserId(String approveUserId) {
		this.approveUserId = approveUserId == null ? null : approveUserId
				.trim();
	}

	public String getTribunalMark() {
		return tribunalMark;
	}

	public void setTribunalMark(String tribunalMark) {
		this.tribunalMark = tribunalMark;
	}
}