package com.zyxy.common.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CaseApproveSuggestExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_approve_suggest
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_approve_suggest
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_approve_suggest
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_approve_suggest
	 * @mbggenerated
	 */
	public CaseApproveSuggestExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_approve_suggest
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_approve_suggest
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_approve_suggest
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_approve_suggest
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_approve_suggest
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_approve_suggest
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_approve_suggest
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_approve_suggest
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_approve_suggest
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_approve_suggest
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table case_approve_suggest
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCaseIdIsNull() {
			addCriterion("CASE_ID is null");
			return (Criteria) this;
		}

		public Criteria andCaseIdIsNotNull() {
			addCriterion("CASE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCaseIdEqualTo(String value) {
			addCriterion("CASE_ID =", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotEqualTo(String value) {
			addCriterion("CASE_ID <>", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdGreaterThan(String value) {
			addCriterion("CASE_ID >", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdGreaterThanOrEqualTo(String value) {
			addCriterion("CASE_ID >=", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLessThan(String value) {
			addCriterion("CASE_ID <", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLessThanOrEqualTo(String value) {
			addCriterion("CASE_ID <=", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLike(String value) {
			addCriterion("CASE_ID like", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotLike(String value) {
			addCriterion("CASE_ID not like", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdIn(List<String> values) {
			addCriterion("CASE_ID in", values, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotIn(List<String> values) {
			addCriterion("CASE_ID not in", values, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdBetween(String value1, String value2) {
			addCriterion("CASE_ID between", value1, value2, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotBetween(String value1, String value2) {
			addCriterion("CASE_ID not between", value1, value2, "caseId");
			return (Criteria) this;
		}

		public Criteria andApproveIdIsNull() {
			addCriterion("APPROVE_ID is null");
			return (Criteria) this;
		}

		public Criteria andApproveIdIsNotNull() {
			addCriterion("APPROVE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andApproveIdEqualTo(String value) {
			addCriterion("APPROVE_ID =", value, "approveId");
			return (Criteria) this;
		}

		public Criteria andApproveIdNotEqualTo(String value) {
			addCriterion("APPROVE_ID <>", value, "approveId");
			return (Criteria) this;
		}

		public Criteria andApproveIdGreaterThan(String value) {
			addCriterion("APPROVE_ID >", value, "approveId");
			return (Criteria) this;
		}

		public Criteria andApproveIdGreaterThanOrEqualTo(String value) {
			addCriterion("APPROVE_ID >=", value, "approveId");
			return (Criteria) this;
		}

		public Criteria andApproveIdLessThan(String value) {
			addCriterion("APPROVE_ID <", value, "approveId");
			return (Criteria) this;
		}

		public Criteria andApproveIdLessThanOrEqualTo(String value) {
			addCriterion("APPROVE_ID <=", value, "approveId");
			return (Criteria) this;
		}

		public Criteria andApproveIdLike(String value) {
			addCriterion("APPROVE_ID like", value, "approveId");
			return (Criteria) this;
		}

		public Criteria andApproveIdNotLike(String value) {
			addCriterion("APPROVE_ID not like", value, "approveId");
			return (Criteria) this;
		}

		public Criteria andApproveIdIn(List<String> values) {
			addCriterion("APPROVE_ID in", values, "approveId");
			return (Criteria) this;
		}

		public Criteria andApproveIdNotIn(List<String> values) {
			addCriterion("APPROVE_ID not in", values, "approveId");
			return (Criteria) this;
		}

		public Criteria andApproveIdBetween(String value1, String value2) {
			addCriterion("APPROVE_ID between", value1, value2, "approveId");
			return (Criteria) this;
		}

		public Criteria andApproveIdNotBetween(String value1, String value2) {
			addCriterion("APPROVE_ID not between", value1, value2, "approveId");
			return (Criteria) this;
		}

		public Criteria andOpinionStatusIsNull() {
			addCriterion("OPINION_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andOpinionStatusIsNotNull() {
			addCriterion("OPINION_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andOpinionStatusEqualTo(String value) {
			addCriterion("OPINION_STATUS =", value, "opinionStatus");
			return (Criteria) this;
		}

		public Criteria andOpinionStatusNotEqualTo(String value) {
			addCriterion("OPINION_STATUS <>", value, "opinionStatus");
			return (Criteria) this;
		}

		public Criteria andOpinionStatusGreaterThan(String value) {
			addCriterion("OPINION_STATUS >", value, "opinionStatus");
			return (Criteria) this;
		}

		public Criteria andOpinionStatusGreaterThanOrEqualTo(String value) {
			addCriterion("OPINION_STATUS >=", value, "opinionStatus");
			return (Criteria) this;
		}

		public Criteria andOpinionStatusLessThan(String value) {
			addCriterion("OPINION_STATUS <", value, "opinionStatus");
			return (Criteria) this;
		}

		public Criteria andOpinionStatusLessThanOrEqualTo(String value) {
			addCriterion("OPINION_STATUS <=", value, "opinionStatus");
			return (Criteria) this;
		}

		public Criteria andOpinionStatusLike(String value) {
			addCriterion("OPINION_STATUS like", value, "opinionStatus");
			return (Criteria) this;
		}

		public Criteria andOpinionStatusNotLike(String value) {
			addCriterion("OPINION_STATUS not like", value, "opinionStatus");
			return (Criteria) this;
		}

		public Criteria andOpinionStatusIn(List<String> values) {
			addCriterion("OPINION_STATUS in", values, "opinionStatus");
			return (Criteria) this;
		}

		public Criteria andOpinionStatusNotIn(List<String> values) {
			addCriterion("OPINION_STATUS not in", values, "opinionStatus");
			return (Criteria) this;
		}

		public Criteria andOpinionStatusBetween(String value1, String value2) {
			addCriterion("OPINION_STATUS between", value1, value2,
					"opinionStatus");
			return (Criteria) this;
		}

		public Criteria andOpinionStatusNotBetween(String value1, String value2) {
			addCriterion("OPINION_STATUS not between", value1, value2,
					"opinionStatus");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIsNull() {
			addCriterion("CREATER_ID is null");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIsNotNull() {
			addCriterion("CREATER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCreaterIdEqualTo(String value) {
			addCriterion("CREATER_ID =", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotEqualTo(String value) {
			addCriterion("CREATER_ID <>", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdGreaterThan(String value) {
			addCriterion("CREATER_ID >", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdGreaterThanOrEqualTo(String value) {
			addCriterion("CREATER_ID >=", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLessThan(String value) {
			addCriterion("CREATER_ID <", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLessThanOrEqualTo(String value) {
			addCriterion("CREATER_ID <=", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLike(String value) {
			addCriterion("CREATER_ID like", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotLike(String value) {
			addCriterion("CREATER_ID not like", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIn(List<String> values) {
			addCriterion("CREATER_ID in", values, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotIn(List<String> values) {
			addCriterion("CREATER_ID not in", values, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdBetween(String value1, String value2) {
			addCriterion("CREATER_ID between", value1, value2, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotBetween(String value1, String value2) {
			addCriterion("CREATER_ID not between", value1, value2, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andMarkIsNull() {
			addCriterion("MARK is null");
			return (Criteria) this;
		}

		public Criteria andMarkIsNotNull() {
			addCriterion("MARK is not null");
			return (Criteria) this;
		}

		public Criteria andMarkEqualTo(String value) {
			addCriterion("MARK =", value, "mark");
			return (Criteria) this;
		}

		public Criteria andMarkNotEqualTo(String value) {
			addCriterion("MARK <>", value, "mark");
			return (Criteria) this;
		}

		public Criteria andMarkGreaterThan(String value) {
			addCriterion("MARK >", value, "mark");
			return (Criteria) this;
		}

		public Criteria andMarkGreaterThanOrEqualTo(String value) {
			addCriterion("MARK >=", value, "mark");
			return (Criteria) this;
		}

		public Criteria andMarkLessThan(String value) {
			addCriterion("MARK <", value, "mark");
			return (Criteria) this;
		}

		public Criteria andMarkLessThanOrEqualTo(String value) {
			addCriterion("MARK <=", value, "mark");
			return (Criteria) this;
		}

		public Criteria andMarkLike(String value) {
			addCriterion("MARK like", value, "mark");
			return (Criteria) this;
		}

		public Criteria andMarkNotLike(String value) {
			addCriterion("MARK not like", value, "mark");
			return (Criteria) this;
		}

		public Criteria andMarkIn(List<String> values) {
			addCriterion("MARK in", values, "mark");
			return (Criteria) this;
		}

		public Criteria andMarkNotIn(List<String> values) {
			addCriterion("MARK not in", values, "mark");
			return (Criteria) this;
		}

		public Criteria andMarkBetween(String value1, String value2) {
			addCriterion("MARK between", value1, value2, "mark");
			return (Criteria) this;
		}

		public Criteria andMarkNotBetween(String value1, String value2) {
			addCriterion("MARK not between", value1, value2, "mark");
			return (Criteria) this;
		}

		public Criteria andSuggestUserDutiesIsNull() {
			addCriterion("SUGGEST_USER_DUTIES is null");
			return (Criteria) this;
		}

		public Criteria andSuggestUserDutiesIsNotNull() {
			addCriterion("SUGGEST_USER_DUTIES is not null");
			return (Criteria) this;
		}

		public Criteria andSuggestUserDutiesEqualTo(String value) {
			addCriterion("SUGGEST_USER_DUTIES =", value, "suggestUserDuties");
			return (Criteria) this;
		}

		public Criteria andSuggestUserDutiesNotEqualTo(String value) {
			addCriterion("SUGGEST_USER_DUTIES <>", value, "suggestUserDuties");
			return (Criteria) this;
		}

		public Criteria andSuggestUserDutiesGreaterThan(String value) {
			addCriterion("SUGGEST_USER_DUTIES >", value, "suggestUserDuties");
			return (Criteria) this;
		}

		public Criteria andSuggestUserDutiesGreaterThanOrEqualTo(String value) {
			addCriterion("SUGGEST_USER_DUTIES >=", value, "suggestUserDuties");
			return (Criteria) this;
		}

		public Criteria andSuggestUserDutiesLessThan(String value) {
			addCriterion("SUGGEST_USER_DUTIES <", value, "suggestUserDuties");
			return (Criteria) this;
		}

		public Criteria andSuggestUserDutiesLessThanOrEqualTo(String value) {
			addCriterion("SUGGEST_USER_DUTIES <=", value, "suggestUserDuties");
			return (Criteria) this;
		}

		public Criteria andSuggestUserDutiesLike(String value) {
			addCriterion("SUGGEST_USER_DUTIES like", value, "suggestUserDuties");
			return (Criteria) this;
		}

		public Criteria andSuggestUserDutiesNotLike(String value) {
			addCriterion("SUGGEST_USER_DUTIES not like", value,
					"suggestUserDuties");
			return (Criteria) this;
		}

		public Criteria andSuggestUserDutiesIn(List<String> values) {
			addCriterion("SUGGEST_USER_DUTIES in", values, "suggestUserDuties");
			return (Criteria) this;
		}

		public Criteria andSuggestUserDutiesNotIn(List<String> values) {
			addCriterion("SUGGEST_USER_DUTIES not in", values,
					"suggestUserDuties");
			return (Criteria) this;
		}

		public Criteria andSuggestUserDutiesBetween(String value1, String value2) {
			addCriterion("SUGGEST_USER_DUTIES between", value1, value2,
					"suggestUserDuties");
			return (Criteria) this;
		}

		public Criteria andSuggestUserDutiesNotBetween(String value1,
				String value2) {
			addCriterion("SUGGEST_USER_DUTIES not between", value1, value2,
					"suggestUserDuties");
			return (Criteria) this;
		}

		public Criteria andIsAuthorizedIsNull() {
			addCriterion("IS_AUTHORIZED is null");
			return (Criteria) this;
		}

		public Criteria andIsAuthorizedIsNotNull() {
			addCriterion("IS_AUTHORIZED is not null");
			return (Criteria) this;
		}

		public Criteria andIsAuthorizedEqualTo(String value) {
			addCriterion("IS_AUTHORIZED =", value, "isAuthorized");
			return (Criteria) this;
		}

		public Criteria andIsAuthorizedNotEqualTo(String value) {
			addCriterion("IS_AUTHORIZED <>", value, "isAuthorized");
			return (Criteria) this;
		}

		public Criteria andIsAuthorizedGreaterThan(String value) {
			addCriterion("IS_AUTHORIZED >", value, "isAuthorized");
			return (Criteria) this;
		}

		public Criteria andIsAuthorizedGreaterThanOrEqualTo(String value) {
			addCriterion("IS_AUTHORIZED >=", value, "isAuthorized");
			return (Criteria) this;
		}

		public Criteria andIsAuthorizedLessThan(String value) {
			addCriterion("IS_AUTHORIZED <", value, "isAuthorized");
			return (Criteria) this;
		}

		public Criteria andIsAuthorizedLessThanOrEqualTo(String value) {
			addCriterion("IS_AUTHORIZED <=", value, "isAuthorized");
			return (Criteria) this;
		}

		public Criteria andIsAuthorizedLike(String value) {
			addCriterion("IS_AUTHORIZED like", value, "isAuthorized");
			return (Criteria) this;
		}

		public Criteria andIsAuthorizedNotLike(String value) {
			addCriterion("IS_AUTHORIZED not like", value, "isAuthorized");
			return (Criteria) this;
		}

		public Criteria andIsAuthorizedIn(List<String> values) {
			addCriterion("IS_AUTHORIZED in", values, "isAuthorized");
			return (Criteria) this;
		}

		public Criteria andIsAuthorizedNotIn(List<String> values) {
			addCriterion("IS_AUTHORIZED not in", values, "isAuthorized");
			return (Criteria) this;
		}

		public Criteria andIsAuthorizedBetween(String value1, String value2) {
			addCriterion("IS_AUTHORIZED between", value1, value2,
					"isAuthorized");
			return (Criteria) this;
		}

		public Criteria andIsAuthorizedNotBetween(String value1, String value2) {
			addCriterion("IS_AUTHORIZED not between", value1, value2,
					"isAuthorized");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table case_approve_suggest
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table case_approve_suggest
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}