package com.zyxy.common.domain;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table case_doc
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class CaseDoc implements Serializable {

	/**
     * case_doc.ID
     * @mbggenerated
     */
    @ApiModelProperty(value = "")
    private String id;
    /**
     * 文件名 case_doc.DOC_NAME
     * @mbggenerated
     */
    @ApiModelProperty(value = "文件名")
    private String docName;
    /**
     * 文书类型 0-撤案决定书，1-裁决书，2-仲裁申请书，3-反请求申请，4-反请求撤案决定书5-仲裁员回避申请书6-仲裁员回避决定书 7-组庭通知书 case_doc.DOC_TYPE
     * @mbggenerated
     */
    @ApiModelProperty(value = "文书类型 0-撤案决定书，1-裁决书，2-仲裁申请书，3-反请求申请，4-反请求撤案决定书5-仲裁员回避申请书6-仲裁员回避决定书 7-组庭通知书")
    private String docType;
    /**
     * 签章状态 case_doc.SIGN_STATUS
     * @mbggenerated
     */
    @ApiModelProperty(value = "签章状态")
    private String signStatus;
    /**
     * 文件ID case_doc.FILE_ID
     * @mbggenerated
     */
    @ApiModelProperty(value = "文件ID")
    private String fileId;
    /**
     * 案件ID case_doc.CASE_ID
     * @mbggenerated
     */
    @ApiModelProperty(value = "案件ID")
    private String caseId;
    /**
     * 业务状态 0-正常，1-废弃 case_doc.STATUS
     * @mbggenerated
     */
    @ApiModelProperty(value = "业务状态 0-正常，1-废弃")
    private String status;
    /**
     * 逻辑状态 case_doc.LOGISTICS_STATUS
     * @mbggenerated
     */
    @ApiModelProperty(value = "逻辑状态")
    private String logisticsStatus;
    /**
     * 文书年编号 case_doc.DOC_YEAR_NUMBER
     * @mbggenerated
     */
    @ApiModelProperty(value = "文书年编号")
    private String docYearNumber;
    /**
     * 文书序列号 case_doc.DOC_SERIAL_NUMBER
     * @mbggenerated
     */
    @ApiModelProperty(value = "文书序列号")
    private String docSerialNumber;
    /**
     * 签章记录表ID case_doc.SIGN_SIGNET_LOG_ID
     * @mbggenerated
     */
    @ApiModelProperty(value = "签章记录表ID")
    private String signSignetLogId;
    /**
     * 创建人ID case_doc.CREATER_ID
     * @mbggenerated
     */
    @ApiModelProperty(value = "创建人ID")
    private String createrId;
    /**
     * 创建时间 case_doc.CREATE_TIME
     * @mbggenerated
     */
    @ApiModelProperty(value = "创建时间")
    private Date createTime;
    /**
     * 更新人ID case_doc.UPDATE_ID
     * @mbggenerated
     */
    @ApiModelProperty(value = "更新人ID")
    private String updateId;
    /**
     * 更新时间 case_doc.UPDATE_TIME
     * @mbggenerated
     */
    @ApiModelProperty(value = "更新时间")
    private Date updateTime;
    /**
     * 请求id case_doc.REQUEST_ID
     * @mbggenerated
     */
    @ApiModelProperty(value = "请求id")
    private String requestId;
    /**
     * 业务id case_doc.BUSI_ID
     * @mbggenerated
     */
    @ApiModelProperty(value = "业务id")
    private String busiId;
    /**
     * case_doc
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return  
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * @param id  
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 文件名
     * @return  文件名
     * @mbggenerated
     */
    public String getDocName() {
        return docName;
    }

    /**
     * 文件名
     * @param docName  文件名
     * @mbggenerated
     */
    public void setDocName(String docName) {
        this.docName = docName == null ? null : docName.trim();
    }

    /**
     * 文书类型 0-撤案决定书，1-裁决书，2-仲裁申请书，3-反请求申请，4-反请求撤案决定书5-仲裁员回避申请书6-仲裁员回避决定书 7-组庭通知书
     * @return  文书类型 0-撤案决定书，1-裁决书，2-仲裁申请书，3-反请求申请，4-反请求撤案决定书5-仲裁员回避申请书6-仲裁员回避决定书 7-组庭通知书
     * @mbggenerated
     */
    public String getDocType() {
        return docType;
    }

    /**
     * 文书类型 0-撤案决定书，1-裁决书，2-仲裁申请书，3-反请求申请，4-反请求撤案决定书5-仲裁员回避申请书6-仲裁员回避决定书 7-组庭通知书
     * @param docType  文书类型 0-撤案决定书，1-裁决书，2-仲裁申请书，3-反请求申请，4-反请求撤案决定书5-仲裁员回避申请书6-仲裁员回避决定书 7-组庭通知书
     * @mbggenerated
     */
    public void setDocType(String docType) {
        this.docType = docType == null ? null : docType.trim();
    }

    /**
     * 签章状态
     * @return  签章状态
     * @mbggenerated
     */
    public String getSignStatus() {
        return signStatus;
    }

    /**
     * 签章状态
     * @param signStatus  签章状态
     * @mbggenerated
     */
    public void setSignStatus(String signStatus) {
        this.signStatus = signStatus == null ? null : signStatus.trim();
    }

    /**
     * 文件ID
     * @return  文件ID
     * @mbggenerated
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * 文件ID
     * @param fileId  文件ID
     * @mbggenerated
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * 案件ID
     * @return  案件ID
     * @mbggenerated
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * 案件ID
     * @param caseId  案件ID
     * @mbggenerated
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * 业务状态 0-正常，1-废弃
     * @return  业务状态 0-正常，1-废弃
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * 业务状态 0-正常，1-废弃
     * @param status  业务状态 0-正常，1-废弃
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * 逻辑状态
     * @return  逻辑状态
     * @mbggenerated
     */
    public String getLogisticsStatus() {
        return logisticsStatus;
    }

    /**
     * 逻辑状态
     * @param logisticsStatus  逻辑状态
     * @mbggenerated
     */
    public void setLogisticsStatus(String logisticsStatus) {
        this.logisticsStatus = logisticsStatus == null ? null : logisticsStatus
                .trim();
    }

    /**
     * 文书年编号
     * @return  文书年编号
     * @mbggenerated
     */
    public String getDocYearNumber() {
        return docYearNumber;
    }

    /**
     * 文书年编号
     * @param docYearNumber  文书年编号
     * @mbggenerated
     */
    public void setDocYearNumber(String docYearNumber) {
        this.docYearNumber = docYearNumber == null ? null : docYearNumber
                .trim();
    }

    /**
     * 文书序列号
     * @return  文书序列号
     * @mbggenerated
     */
    public String getDocSerialNumber() {
        return docSerialNumber;
    }

    /**
     * 文书序列号
     * @param docSerialNumber  文书序列号
     * @mbggenerated
     */
    public void setDocSerialNumber(String docSerialNumber) {
        this.docSerialNumber = docSerialNumber == null ? null : docSerialNumber
                .trim();
    }

    /**
     * 签章记录表ID
     * @return  签章记录表ID
     * @mbggenerated
     */
    public String getSignSignetLogId() {
        return signSignetLogId;
    }

    /**
     * 签章记录表ID
     * @param signSignetLogId  签章记录表ID
     * @mbggenerated
     */
    public void setSignSignetLogId(String signSignetLogId) {
        this.signSignetLogId = signSignetLogId == null ? null : signSignetLogId
                .trim();
    }

    /**
     * 创建人ID
     * @return  创建人ID
     * @mbggenerated
     */
    public String getCreaterId() {
        return createrId;
    }

    /**
     * 创建人ID
     * @param createrId  创建人ID
     * @mbggenerated
     */
    public void setCreaterId(String createrId) {
        this.createrId = createrId == null ? null : createrId.trim();
    }

    /**
     * 创建时间
     * @return  创建时间
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 创建时间
     * @param createTime  创建时间
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 更新人ID
     * @return  更新人ID
     * @mbggenerated
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * 更新人ID
     * @param updateId  更新人ID
     * @mbggenerated
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * 更新时间
     * @return  更新时间
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 更新时间
     * @param updateTime  更新时间
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 请求id
     * @return  请求id
     * @mbggenerated
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * 请求id
     * @param requestId  请求id
     * @mbggenerated
     */
    public void setRequestId(String requestId) {
        this.requestId = requestId == null ? null : requestId.trim();
    }

    /**
     * 业务id
     * @return  业务id
     * @mbggenerated
     */
    public String getBusiId() {
        return busiId;
    }

    /**
     * 业务id
     * @param busiId  业务id
     * @mbggenerated
     */
    public void setBusiId(String busiId) {
        this.busiId = busiId == null ? null : busiId.trim();
    }

    public static void main(String[] args) {
        StringBuilder builder = new StringBuilder();
        builder.append(",123,");
        System.out.println(builder.substring(0,builder.lastIndexOf(",")));
    }
}