package com.zyxy.common.domain;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * @author tanquan
 *
 * case_time_set
 *
 * @mbggenerated do_not_delete_during_merge
 */
@ApiModel(value ="CaseTimeSet")
public class CaseTimeSet implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_time_set.ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "")
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_time_set.NODE_ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "")
	private Integer nodeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_time_set.TIME_SET
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "")
	private Long timeSet;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_time_set.REMARK
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "")
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_time_set
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_time_set.ID
	 * @return  the value of case_time_set.ID
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_time_set.ID
	 * @param id  the value for case_time_set.ID
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_time_set.NODE_ID
	 * @return  the value of case_time_set.NODE_ID
	 * @mbggenerated
	 */
	public Integer getNodeId() {
		return nodeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_time_set.NODE_ID
	 * @param nodeId  the value for case_time_set.NODE_ID
	 * @mbggenerated
	 */
	public void setNodeId(Integer nodeId) {
		this.nodeId = nodeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_time_set.TIME_SET
	 * @return  the value of case_time_set.TIME_SET
	 * @mbggenerated
	 */
	public Long getTimeSet() {
		return timeSet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_time_set.TIME_SET
	 * @param timeSet  the value for case_time_set.TIME_SET
	 * @mbggenerated
	 */
	public void setTimeSet(Long timeSet) {
		this.timeSet = timeSet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_time_set.REMARK
	 * @return  the value of case_time_set.REMARK
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_time_set.REMARK
	 * @param remark  the value for case_time_set.REMARK
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}