package com.zyxy.common.domain;

import java.io.Serializable;

public class CaseAvoidRecordWithBLOBs extends CaseAvoidRecord implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_avoid_record.AVOID_REQUST
	 * @mbggenerated
	 */
	private String avoidRequst;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_avoid_record.AVOID_REASON
	 * @mbggenerated
	 */
	private String avoidReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_avoid_record.FAIL_REASON
	 * @mbggenerated
	 */
	private String failReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_avoid_record.AVOID_REQUST
	 * @return  the value of case_avoid_record.AVOID_REQUST
	 * @mbggenerated
	 */
	public String getAvoidRequst() {
		return avoidRequst;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_avoid_record.AVOID_REQUST
	 * @param avoidRequst  the value for case_avoid_record.AVOID_REQUST
	 * @mbggenerated
	 */
	public void setAvoidRequst(String avoidRequst) {
		this.avoidRequst = avoidRequst == null ? null : avoidRequst.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_avoid_record.AVOID_REASON
	 * @return  the value of case_avoid_record.AVOID_REASON
	 * @mbggenerated
	 */
	public String getAvoidReason() {
		return avoidReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_avoid_record.AVOID_REASON
	 * @param avoidReason  the value for case_avoid_record.AVOID_REASON
	 * @mbggenerated
	 */
	public void setAvoidReason(String avoidReason) {
		this.avoidReason = avoidReason == null ? null : avoidReason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_avoid_record.FAIL_REASON
	 * @return  the value of case_avoid_record.FAIL_REASON
	 * @mbggenerated
	 */
	public String getFailReason() {
		return failReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_avoid_record.FAIL_REASON
	 * @param failReason  the value for case_avoid_record.FAIL_REASON
	 * @mbggenerated
	 */
	public void setFailReason(String failReason) {
		this.failReason = failReason == null ? null : failReason.trim();
	}
}