package com.zyxy.common.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CaseRejoinRecordExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	public CaseRejoinRecordExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCaseIdIsNull() {
			addCriterion("CASE_ID is null");
			return (Criteria) this;
		}

		public Criteria andCaseIdIsNotNull() {
			addCriterion("CASE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCaseIdEqualTo(String value) {
			addCriterion("CASE_ID =", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotEqualTo(String value) {
			addCriterion("CASE_ID <>", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdGreaterThan(String value) {
			addCriterion("CASE_ID >", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdGreaterThanOrEqualTo(String value) {
			addCriterion("CASE_ID >=", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLessThan(String value) {
			addCriterion("CASE_ID <", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLessThanOrEqualTo(String value) {
			addCriterion("CASE_ID <=", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLike(String value) {
			addCriterion("CASE_ID like", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotLike(String value) {
			addCriterion("CASE_ID not like", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdIn(List<String> values) {
			addCriterion("CASE_ID in", values, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotIn(List<String> values) {
			addCriterion("CASE_ID not in", values, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdBetween(String value1, String value2) {
			addCriterion("CASE_ID between", value1, value2, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotBetween(String value1, String value2) {
			addCriterion("CASE_ID not between", value1, value2, "caseId");
			return (Criteria) this;
		}

		public Criteria andRequestIdIsNull() {
			addCriterion("REQUEST_ID is null");
			return (Criteria) this;
		}

		public Criteria andRequestIdIsNotNull() {
			addCriterion("REQUEST_ID is not null");
			return (Criteria) this;
		}

		public Criteria andRequestIdEqualTo(String value) {
			addCriterion("REQUEST_ID =", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdNotEqualTo(String value) {
			addCriterion("REQUEST_ID <>", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdGreaterThan(String value) {
			addCriterion("REQUEST_ID >", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdGreaterThanOrEqualTo(String value) {
			addCriterion("REQUEST_ID >=", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdLessThan(String value) {
			addCriterion("REQUEST_ID <", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdLessThanOrEqualTo(String value) {
			addCriterion("REQUEST_ID <=", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdLike(String value) {
			addCriterion("REQUEST_ID like", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdNotLike(String value) {
			addCriterion("REQUEST_ID not like", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdIn(List<String> values) {
			addCriterion("REQUEST_ID in", values, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdNotIn(List<String> values) {
			addCriterion("REQUEST_ID not in", values, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdBetween(String value1, String value2) {
			addCriterion("REQUEST_ID between", value1, value2, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdNotBetween(String value1, String value2) {
			addCriterion("REQUEST_ID not between", value1, value2, "requestId");
			return (Criteria) this;
		}

		public Criteria andRejoinIdIsNull() {
			addCriterion("REJOIN_ID is null");
			return (Criteria) this;
		}

		public Criteria andRejoinIdIsNotNull() {
			addCriterion("REJOIN_ID is not null");
			return (Criteria) this;
		}

		public Criteria andRejoinIdEqualTo(String value) {
			addCriterion("REJOIN_ID =", value, "rejoinId");
			return (Criteria) this;
		}

		public Criteria andRejoinIdNotEqualTo(String value) {
			addCriterion("REJOIN_ID <>", value, "rejoinId");
			return (Criteria) this;
		}

		public Criteria andRejoinIdGreaterThan(String value) {
			addCriterion("REJOIN_ID >", value, "rejoinId");
			return (Criteria) this;
		}

		public Criteria andRejoinIdGreaterThanOrEqualTo(String value) {
			addCriterion("REJOIN_ID >=", value, "rejoinId");
			return (Criteria) this;
		}

		public Criteria andRejoinIdLessThan(String value) {
			addCriterion("REJOIN_ID <", value, "rejoinId");
			return (Criteria) this;
		}

		public Criteria andRejoinIdLessThanOrEqualTo(String value) {
			addCriterion("REJOIN_ID <=", value, "rejoinId");
			return (Criteria) this;
		}

		public Criteria andRejoinIdLike(String value) {
			addCriterion("REJOIN_ID like", value, "rejoinId");
			return (Criteria) this;
		}

		public Criteria andRejoinIdNotLike(String value) {
			addCriterion("REJOIN_ID not like", value, "rejoinId");
			return (Criteria) this;
		}

		public Criteria andRejoinIdIn(List<String> values) {
			addCriterion("REJOIN_ID in", values, "rejoinId");
			return (Criteria) this;
		}

		public Criteria andRejoinIdNotIn(List<String> values) {
			addCriterion("REJOIN_ID not in", values, "rejoinId");
			return (Criteria) this;
		}

		public Criteria andRejoinIdBetween(String value1, String value2) {
			addCriterion("REJOIN_ID between", value1, value2, "rejoinId");
			return (Criteria) this;
		}

		public Criteria andRejoinIdNotBetween(String value1, String value2) {
			addCriterion("REJOIN_ID not between", value1, value2, "rejoinId");
			return (Criteria) this;
		}

		public Criteria andCounterclaimFlagIsNull() {
			addCriterion("COUNTERCLAIM_FLAG is null");
			return (Criteria) this;
		}

		public Criteria andCounterclaimFlagIsNotNull() {
			addCriterion("COUNTERCLAIM_FLAG is not null");
			return (Criteria) this;
		}

		public Criteria andCounterclaimFlagEqualTo(String value) {
			addCriterion("COUNTERCLAIM_FLAG =", value, "counterclaimFlag");
			return (Criteria) this;
		}

		public Criteria andCounterclaimFlagNotEqualTo(String value) {
			addCriterion("COUNTERCLAIM_FLAG <>", value, "counterclaimFlag");
			return (Criteria) this;
		}

		public Criteria andCounterclaimFlagGreaterThan(String value) {
			addCriterion("COUNTERCLAIM_FLAG >", value, "counterclaimFlag");
			return (Criteria) this;
		}

		public Criteria andCounterclaimFlagGreaterThanOrEqualTo(String value) {
			addCriterion("COUNTERCLAIM_FLAG >=", value, "counterclaimFlag");
			return (Criteria) this;
		}

		public Criteria andCounterclaimFlagLessThan(String value) {
			addCriterion("COUNTERCLAIM_FLAG <", value, "counterclaimFlag");
			return (Criteria) this;
		}

		public Criteria andCounterclaimFlagLessThanOrEqualTo(String value) {
			addCriterion("COUNTERCLAIM_FLAG <=", value, "counterclaimFlag");
			return (Criteria) this;
		}

		public Criteria andCounterclaimFlagLike(String value) {
			addCriterion("COUNTERCLAIM_FLAG like", value, "counterclaimFlag");
			return (Criteria) this;
		}

		public Criteria andCounterclaimFlagNotLike(String value) {
			addCriterion("COUNTERCLAIM_FLAG not like", value,
					"counterclaimFlag");
			return (Criteria) this;
		}

		public Criteria andCounterclaimFlagIn(List<String> values) {
			addCriterion("COUNTERCLAIM_FLAG in", values, "counterclaimFlag");
			return (Criteria) this;
		}

		public Criteria andCounterclaimFlagNotIn(List<String> values) {
			addCriterion("COUNTERCLAIM_FLAG not in", values, "counterclaimFlag");
			return (Criteria) this;
		}

		public Criteria andCounterclaimFlagBetween(String value1, String value2) {
			addCriterion("COUNTERCLAIM_FLAG between", value1, value2,
					"counterclaimFlag");
			return (Criteria) this;
		}

		public Criteria andCounterclaimFlagNotBetween(String value1,
				String value2) {
			addCriterion("COUNTERCLAIM_FLAG not between", value1, value2,
					"counterclaimFlag");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIsNull() {
			addCriterion("CREATER_ID is null");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIsNotNull() {
			addCriterion("CREATER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCreaterIdEqualTo(String value) {
			addCriterion("CREATER_ID =", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotEqualTo(String value) {
			addCriterion("CREATER_ID <>", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdGreaterThan(String value) {
			addCriterion("CREATER_ID >", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdGreaterThanOrEqualTo(String value) {
			addCriterion("CREATER_ID >=", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLessThan(String value) {
			addCriterion("CREATER_ID <", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLessThanOrEqualTo(String value) {
			addCriterion("CREATER_ID <=", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLike(String value) {
			addCriterion("CREATER_ID like", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotLike(String value) {
			addCriterion("CREATER_ID not like", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIn(List<String> values) {
			addCriterion("CREATER_ID in", values, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotIn(List<String> values) {
			addCriterion("CREATER_ID not in", values, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdBetween(String value1, String value2) {
			addCriterion("CREATER_ID between", value1, value2, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotBetween(String value1, String value2) {
			addCriterion("CREATER_ID not between", value1, value2, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andChangeIdIsNull() {
			addCriterion("CHANGE_ID is null");
			return (Criteria) this;
		}

		public Criteria andChangeIdIsNotNull() {
			addCriterion("CHANGE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andChangeIdEqualTo(String value) {
			addCriterion("CHANGE_ID =", value, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdNotEqualTo(String value) {
			addCriterion("CHANGE_ID <>", value, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdGreaterThan(String value) {
			addCriterion("CHANGE_ID >", value, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdGreaterThanOrEqualTo(String value) {
			addCriterion("CHANGE_ID >=", value, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdLessThan(String value) {
			addCriterion("CHANGE_ID <", value, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdLessThanOrEqualTo(String value) {
			addCriterion("CHANGE_ID <=", value, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdLike(String value) {
			addCriterion("CHANGE_ID like", value, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdNotLike(String value) {
			addCriterion("CHANGE_ID not like", value, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdIn(List<String> values) {
			addCriterion("CHANGE_ID in", values, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdNotIn(List<String> values) {
			addCriterion("CHANGE_ID not in", values, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdBetween(String value1, String value2) {
			addCriterion("CHANGE_ID between", value1, value2, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdNotBetween(String value1, String value2) {
			addCriterion("CHANGE_ID not between", value1, value2, "changeId");
			return (Criteria) this;
		}

		public Criteria andRejoinTyepIsNull() {
			addCriterion("REJOIN_TYEP is null");
			return (Criteria) this;
		}

		public Criteria andRejoinTyepIsNotNull() {
			addCriterion("REJOIN_TYEP is not null");
			return (Criteria) this;
		}

		public Criteria andRejoinTyepEqualTo(String value) {
			addCriterion("REJOIN_TYEP =", value, "rejoinTyep");
			return (Criteria) this;
		}

		public Criteria andRejoinTyepNotEqualTo(String value) {
			addCriterion("REJOIN_TYEP <>", value, "rejoinTyep");
			return (Criteria) this;
		}

		public Criteria andRejoinTyepGreaterThan(String value) {
			addCriterion("REJOIN_TYEP >", value, "rejoinTyep");
			return (Criteria) this;
		}

		public Criteria andRejoinTyepGreaterThanOrEqualTo(String value) {
			addCriterion("REJOIN_TYEP >=", value, "rejoinTyep");
			return (Criteria) this;
		}

		public Criteria andRejoinTyepLessThan(String value) {
			addCriterion("REJOIN_TYEP <", value, "rejoinTyep");
			return (Criteria) this;
		}

		public Criteria andRejoinTyepLessThanOrEqualTo(String value) {
			addCriterion("REJOIN_TYEP <=", value, "rejoinTyep");
			return (Criteria) this;
		}

		public Criteria andRejoinTyepLike(String value) {
			addCriterion("REJOIN_TYEP like", value, "rejoinTyep");
			return (Criteria) this;
		}

		public Criteria andRejoinTyepNotLike(String value) {
			addCriterion("REJOIN_TYEP not like", value, "rejoinTyep");
			return (Criteria) this;
		}

		public Criteria andRejoinTyepIn(List<String> values) {
			addCriterion("REJOIN_TYEP in", values, "rejoinTyep");
			return (Criteria) this;
		}

		public Criteria andRejoinTyepNotIn(List<String> values) {
			addCriterion("REJOIN_TYEP not in", values, "rejoinTyep");
			return (Criteria) this;
		}

		public Criteria andRejoinTyepBetween(String value1, String value2) {
			addCriterion("REJOIN_TYEP between", value1, value2, "rejoinTyep");
			return (Criteria) this;
		}

		public Criteria andRejoinTyepNotBetween(String value1, String value2) {
			addCriterion("REJOIN_TYEP not between", value1, value2,
					"rejoinTyep");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * case_rejoin_record
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}