package com.zyxy.common.domain;

import java.io.Serializable;
import java.util.Date;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * @author tanquan
 *
 * case_rejoin_record
 *
 * @mbggenerated do_not_delete_during_merge
 */
@ApiModel(value ="CaseRejoinRecord")
public class CaseRejoinRecord implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_rejoin_record.ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "编号")
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_rejoin_record.CASE_ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "案件ID")
	private String caseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_rejoin_record.REQUEST_ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "请求ID")
	private String requestId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_rejoin_record.REJOIN_ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "答辩人ID")
	private String rejoinId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_rejoin_record.COUNTERCLAIM_FLAG
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "请求标志，0- 正请求，1-反请求")
	private String counterclaimFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_rejoin_record.STATUS
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "状态，0- 草稿 1- 有效")
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_rejoin_record.CREATER_ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "创建人ID")
	private String createrId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_rejoin_record.CREATE_TIME
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "创建时间")
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_rejoin_record.CHANGE_ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "仲裁变更ID")
	private String changeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column case_rejoin_record.REJOIN_TYEP
	 * @mbggenerated
	 */
	private String rejoinTyep;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_rejoin_record.ID
	 * @return  the value of case_rejoin_record.ID
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_rejoin_record.ID
	 * @param id  the value for case_rejoin_record.ID
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_rejoin_record.CASE_ID
	 * @return  the value of case_rejoin_record.CASE_ID
	 * @mbggenerated
	 */
	public String getCaseId() {
		return caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_rejoin_record.CASE_ID
	 * @param caseId  the value for case_rejoin_record.CASE_ID
	 * @mbggenerated
	 */
	public void setCaseId(String caseId) {
		this.caseId = caseId == null ? null : caseId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_rejoin_record.REQUEST_ID
	 * @return  the value of case_rejoin_record.REQUEST_ID
	 * @mbggenerated
	 */
	public String getRequestId() {
		return requestId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_rejoin_record.REQUEST_ID
	 * @param requestId  the value for case_rejoin_record.REQUEST_ID
	 * @mbggenerated
	 */
	public void setRequestId(String requestId) {
		this.requestId = requestId == null ? null : requestId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_rejoin_record.REJOIN_ID
	 * @return  the value of case_rejoin_record.REJOIN_ID
	 * @mbggenerated
	 */
	public String getRejoinId() {
		return rejoinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_rejoin_record.REJOIN_ID
	 * @param rejoinId  the value for case_rejoin_record.REJOIN_ID
	 * @mbggenerated
	 */
	public void setRejoinId(String rejoinId) {
		this.rejoinId = rejoinId == null ? null : rejoinId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_rejoin_record.COUNTERCLAIM_FLAG
	 * @return  the value of case_rejoin_record.COUNTERCLAIM_FLAG
	 * @mbggenerated
	 */
	public String getCounterclaimFlag() {
		return counterclaimFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_rejoin_record.COUNTERCLAIM_FLAG
	 * @param counterclaimFlag  the value for case_rejoin_record.COUNTERCLAIM_FLAG
	 * @mbggenerated
	 */
	public void setCounterclaimFlag(String counterclaimFlag) {
		this.counterclaimFlag = counterclaimFlag == null ? null
				: counterclaimFlag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_rejoin_record.STATUS
	 * @return  the value of case_rejoin_record.STATUS
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_rejoin_record.STATUS
	 * @param status  the value for case_rejoin_record.STATUS
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_rejoin_record.CREATER_ID
	 * @return  the value of case_rejoin_record.CREATER_ID
	 * @mbggenerated
	 */
	public String getCreaterId() {
		return createrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_rejoin_record.CREATER_ID
	 * @param createrId  the value for case_rejoin_record.CREATER_ID
	 * @mbggenerated
	 */
	public void setCreaterId(String createrId) {
		this.createrId = createrId == null ? null : createrId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_rejoin_record.CREATE_TIME
	 * @return  the value of case_rejoin_record.CREATE_TIME
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_rejoin_record.CREATE_TIME
	 * @param createTime  the value for case_rejoin_record.CREATE_TIME
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_rejoin_record.CHANGE_ID
	 * @return  the value of case_rejoin_record.CHANGE_ID
	 * @mbggenerated
	 */
	public String getChangeId() {
		return changeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_rejoin_record.CHANGE_ID
	 * @param changeId  the value for case_rejoin_record.CHANGE_ID
	 * @mbggenerated
	 */
	public void setChangeId(String changeId) {
		this.changeId = changeId == null ? null : changeId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column case_rejoin_record.REJOIN_TYEP
	 * @return  the value of case_rejoin_record.REJOIN_TYEP
	 * @mbggenerated
	 */
	public String getRejoinTyep() {
		return rejoinTyep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column case_rejoin_record.REJOIN_TYEP
	 * @param rejoinTyep  the value for case_rejoin_record.REJOIN_TYEP
	 * @mbggenerated
	 */
	public void setRejoinTyep(String rejoinTyep) {
		this.rejoinTyep = rejoinTyep == null ? null : rejoinTyep.trim();
	}
}