package com.zyxy.common.domain;

import java.io.Serializable;
import java.util.Date;

import com.zyxy.common.constants.RegexpConstant;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;

/**
 * @author tanquan
 * 
 *   和解记录表
 *
 * compromise_record
 *
 * @mbggenerated do_not_delete_during_merge
 */
@ApiModel(value ="CompromiseRecord")
public class CompromiseRecord implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compromise_record.ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "编号")
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compromise_record.CASE_ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "案件ID")
	@NotNull(message = "案件id不能为空")
	private String caseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compromise_record.SENDER_TYPE
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "发送方类型。0- 申请人,1- 被申请人,2- 仲裁秘书,3- 仲裁员")
	@NotNull(message = "发送方类型不能为空")
	@Pattern(regexp = RegexpConstant.SENDER_TYPE_REGEX, message = "发送方类型出错")
	private String senderType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compromise_record.CONTENT_TYPE
	 * @mbggenerated
	 */
	private String contentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compromise_record.CREATER_ID
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "创建人")
	private String createrId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compromise_record.CREATE_TIME
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "创建时间")
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compromise_record.CONTENT
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "内容")
	@NotNull(message = "内容不能为空")
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table compromise_record
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compromise_record.ID
	 * @return  the value of compromise_record.ID
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compromise_record.ID
	 * @param id  the value for compromise_record.ID
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compromise_record.CASE_ID
	 * @return  the value of compromise_record.CASE_ID
	 * @mbggenerated
	 */
	public String getCaseId() {
		return caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compromise_record.CASE_ID
	 * @param caseId  the value for compromise_record.CASE_ID
	 * @mbggenerated
	 */
	public void setCaseId(String caseId) {
		this.caseId = caseId == null ? null : caseId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compromise_record.SENDER_TYPE
	 * @return  the value of compromise_record.SENDER_TYPE
	 * @mbggenerated
	 */
	public String getSenderType() {
		return senderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compromise_record.SENDER_TYPE
	 * @param senderType  the value for compromise_record.SENDER_TYPE
	 * @mbggenerated
	 */
	public void setSenderType(String senderType) {
		this.senderType = senderType == null ? null : senderType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compromise_record.CONTENT_TYPE
	 * @return  the value of compromise_record.CONTENT_TYPE
	 * @mbggenerated
	 */
	public String getContentType() {
		return contentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compromise_record.CONTENT_TYPE
	 * @param contentType  the value for compromise_record.CONTENT_TYPE
	 * @mbggenerated
	 */
	public void setContentType(String contentType) {
		this.contentType = contentType == null ? null : contentType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compromise_record.CREATER_ID
	 * @return  the value of compromise_record.CREATER_ID
	 * @mbggenerated
	 */
	public String getCreaterId() {
		return createrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compromise_record.CREATER_ID
	 * @param createrId  the value for compromise_record.CREATER_ID
	 * @mbggenerated
	 */
	public void setCreaterId(String createrId) {
		this.createrId = createrId == null ? null : createrId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compromise_record.CREATE_TIME
	 * @return  the value of compromise_record.CREATE_TIME
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compromise_record.CREATE_TIME
	 * @param createTime  the value for compromise_record.CREATE_TIME
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compromise_record.CONTENT
	 * @return  the value of compromise_record.CONTENT
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compromise_record.CONTENT
	 * @param content  the value for compromise_record.CONTENT
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}