package com.zyxy.common.domain;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table manager_info
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class ManagerInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   职务 0-立案秘书，1-立案部长，2-仲裁秘书，3-仲裁部长，4-主任
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.DUTIES
     *
     * @mbggenerated
     */
    private String duties;

    /**
     * Database Column Remarks:
     *   专长
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.SPECIALTY
     *
     * @mbggenerated
     */
    private String specialty;

    /**
     * Database Column Remarks:
     *   状态 0-正常，1-注销
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   创建者ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.CREATER_ID
     *
     * @mbggenerated
     */
    private String createrId;

    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.CREATE_DATE
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * Database Column Remarks:
     *   编辑者ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.UPDATE_ID
     *
     * @mbggenerated
     */
    private String updateId;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.UPDATE_DATE
     *
     * @mbggenerated
     */
    private String updateDate;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * Database Column Remarks:
     *   用户编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manager_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.ID
     *
     * @return the value of manager_info.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.ID
     *
     * @param id the value for manager_info.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.DUTIES
     *
     * @return the value of manager_info.DUTIES
     *
     * @mbggenerated
     */
    public String getDuties() {
        return duties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.DUTIES
     *
     * @param duties the value for manager_info.DUTIES
     *
     * @mbggenerated
     */
    public void setDuties(String duties) {
        this.duties = duties == null ? null : duties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.SPECIALTY
     *
     * @return the value of manager_info.SPECIALTY
     *
     * @mbggenerated
     */
    public String getSpecialty() {
        return specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.SPECIALTY
     *
     * @param specialty the value for manager_info.SPECIALTY
     *
     * @mbggenerated
     */
    public void setSpecialty(String specialty) {
        this.specialty = specialty == null ? null : specialty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.STATUS
     *
     * @return the value of manager_info.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.STATUS
     *
     * @param status the value for manager_info.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.CREATER_ID
     *
     * @return the value of manager_info.CREATER_ID
     *
     * @mbggenerated
     */
    public String getCreaterId() {
        return createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.CREATER_ID
     *
     * @param createrId the value for manager_info.CREATER_ID
     *
     * @mbggenerated
     */
    public void setCreaterId(String createrId) {
        this.createrId = createrId == null ? null : createrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.CREATE_DATE
     *
     * @return the value of manager_info.CREATE_DATE
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.CREATE_DATE
     *
     * @param createDate the value for manager_info.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.CREATE_TIME
     *
     * @return the value of manager_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.CREATE_TIME
     *
     * @param createTime the value for manager_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.UPDATE_ID
     *
     * @return the value of manager_info.UPDATE_ID
     *
     * @mbggenerated
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.UPDATE_ID
     *
     * @param updateId the value for manager_info.UPDATE_ID
     *
     * @mbggenerated
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.UPDATE_DATE
     *
     * @return the value of manager_info.UPDATE_DATE
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.UPDATE_DATE
     *
     * @param updateDate the value for manager_info.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.UPDATE_TIME
     *
     * @return the value of manager_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.UPDATE_TIME
     *
     * @param updateTime the value for manager_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.USER_ID
     *
     * @return the value of manager_info.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.USER_ID
     *
     * @param userId the value for manager_info.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}