package com.zyxy.common.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QuizRecordExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	public QuizRecordExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCaseIdIsNull() {
			addCriterion("CASE_ID is null");
			return (Criteria) this;
		}

		public Criteria andCaseIdIsNotNull() {
			addCriterion("CASE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCaseIdEqualTo(String value) {
			addCriterion("CASE_ID =", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotEqualTo(String value) {
			addCriterion("CASE_ID <>", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdGreaterThan(String value) {
			addCriterion("CASE_ID >", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdGreaterThanOrEqualTo(String value) {
			addCriterion("CASE_ID >=", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLessThan(String value) {
			addCriterion("CASE_ID <", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLessThanOrEqualTo(String value) {
			addCriterion("CASE_ID <=", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLike(String value) {
			addCriterion("CASE_ID like", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotLike(String value) {
			addCriterion("CASE_ID not like", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdIn(List<String> values) {
			addCriterion("CASE_ID in", values, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotIn(List<String> values) {
			addCriterion("CASE_ID not in", values, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdBetween(String value1, String value2) {
			addCriterion("CASE_ID between", value1, value2, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotBetween(String value1, String value2) {
			addCriterion("CASE_ID not between", value1, value2, "caseId");
			return (Criteria) this;
		}

		public Criteria andQuizObjectIsNull() {
			addCriterion("QUIZ_OBJECT is null");
			return (Criteria) this;
		}

		public Criteria andQuizObjectIsNotNull() {
			addCriterion("QUIZ_OBJECT is not null");
			return (Criteria) this;
		}

		public Criteria andQuizObjectEqualTo(String value) {
			addCriterion("QUIZ_OBJECT =", value, "quizObject");
			return (Criteria) this;
		}

		public Criteria andQuizObjectNotEqualTo(String value) {
			addCriterion("QUIZ_OBJECT <>", value, "quizObject");
			return (Criteria) this;
		}

		public Criteria andQuizObjectGreaterThan(String value) {
			addCriterion("QUIZ_OBJECT >", value, "quizObject");
			return (Criteria) this;
		}

		public Criteria andQuizObjectGreaterThanOrEqualTo(String value) {
			addCriterion("QUIZ_OBJECT >=", value, "quizObject");
			return (Criteria) this;
		}

		public Criteria andQuizObjectLessThan(String value) {
			addCriterion("QUIZ_OBJECT <", value, "quizObject");
			return (Criteria) this;
		}

		public Criteria andQuizObjectLessThanOrEqualTo(String value) {
			addCriterion("QUIZ_OBJECT <=", value, "quizObject");
			return (Criteria) this;
		}

		public Criteria andQuizObjectLike(String value) {
			addCriterion("QUIZ_OBJECT like", value, "quizObject");
			return (Criteria) this;
		}

		public Criteria andQuizObjectNotLike(String value) {
			addCriterion("QUIZ_OBJECT not like", value, "quizObject");
			return (Criteria) this;
		}

		public Criteria andQuizObjectIn(List<String> values) {
			addCriterion("QUIZ_OBJECT in", values, "quizObject");
			return (Criteria) this;
		}

		public Criteria andQuizObjectNotIn(List<String> values) {
			addCriterion("QUIZ_OBJECT not in", values, "quizObject");
			return (Criteria) this;
		}

		public Criteria andQuizObjectBetween(String value1, String value2) {
			addCriterion("QUIZ_OBJECT between", value1, value2, "quizObject");
			return (Criteria) this;
		}

		public Criteria andQuizObjectNotBetween(String value1, String value2) {
			addCriterion("QUIZ_OBJECT not between", value1, value2,
					"quizObject");
			return (Criteria) this;
		}

		public Criteria andAnswerTimeIsNull() {
			addCriterion("ANSWER_TIME is null");
			return (Criteria) this;
		}

		public Criteria andAnswerTimeIsNotNull() {
			addCriterion("ANSWER_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andAnswerTimeEqualTo(Date value) {
			addCriterion("ANSWER_TIME =", value, "answerTime");
			return (Criteria) this;
		}

		public Criteria andAnswerTimeNotEqualTo(Date value) {
			addCriterion("ANSWER_TIME <>", value, "answerTime");
			return (Criteria) this;
		}

		public Criteria andAnswerTimeGreaterThan(Date value) {
			addCriterion("ANSWER_TIME >", value, "answerTime");
			return (Criteria) this;
		}

		public Criteria andAnswerTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("ANSWER_TIME >=", value, "answerTime");
			return (Criteria) this;
		}

		public Criteria andAnswerTimeLessThan(Date value) {
			addCriterion("ANSWER_TIME <", value, "answerTime");
			return (Criteria) this;
		}

		public Criteria andAnswerTimeLessThanOrEqualTo(Date value) {
			addCriterion("ANSWER_TIME <=", value, "answerTime");
			return (Criteria) this;
		}

		public Criteria andAnswerTimeIn(List<Date> values) {
			addCriterion("ANSWER_TIME in", values, "answerTime");
			return (Criteria) this;
		}

		public Criteria andAnswerTimeNotIn(List<Date> values) {
			addCriterion("ANSWER_TIME not in", values, "answerTime");
			return (Criteria) this;
		}

		public Criteria andAnswerTimeBetween(Date value1, Date value2) {
			addCriterion("ANSWER_TIME between", value1, value2, "answerTime");
			return (Criteria) this;
		}

		public Criteria andAnswerTimeNotBetween(Date value1, Date value2) {
			addCriterion("ANSWER_TIME not between", value1, value2,
					"answerTime");
			return (Criteria) this;
		}

		public Criteria andRespondentAnswerTimeIsNull() {
			addCriterion("RESPONDENT_ANSWER_TIME is null");
			return (Criteria) this;
		}

		public Criteria andRespondentAnswerTimeIsNotNull() {
			addCriterion("RESPONDENT_ANSWER_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andRespondentAnswerTimeEqualTo(Date value) {
			addCriterion("RESPONDENT_ANSWER_TIME =", value,
					"respondentAnswerTime");
			return (Criteria) this;
		}

		public Criteria andRespondentAnswerTimeNotEqualTo(Date value) {
			addCriterion("RESPONDENT_ANSWER_TIME <>", value,
					"respondentAnswerTime");
			return (Criteria) this;
		}

		public Criteria andRespondentAnswerTimeGreaterThan(Date value) {
			addCriterion("RESPONDENT_ANSWER_TIME >", value,
					"respondentAnswerTime");
			return (Criteria) this;
		}

		public Criteria andRespondentAnswerTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("RESPONDENT_ANSWER_TIME >=", value,
					"respondentAnswerTime");
			return (Criteria) this;
		}

		public Criteria andRespondentAnswerTimeLessThan(Date value) {
			addCriterion("RESPONDENT_ANSWER_TIME <", value,
					"respondentAnswerTime");
			return (Criteria) this;
		}

		public Criteria andRespondentAnswerTimeLessThanOrEqualTo(Date value) {
			addCriterion("RESPONDENT_ANSWER_TIME <=", value,
					"respondentAnswerTime");
			return (Criteria) this;
		}

		public Criteria andRespondentAnswerTimeIn(List<Date> values) {
			addCriterion("RESPONDENT_ANSWER_TIME in", values,
					"respondentAnswerTime");
			return (Criteria) this;
		}

		public Criteria andRespondentAnswerTimeNotIn(List<Date> values) {
			addCriterion("RESPONDENT_ANSWER_TIME not in", values,
					"respondentAnswerTime");
			return (Criteria) this;
		}

		public Criteria andRespondentAnswerTimeBetween(Date value1, Date value2) {
			addCriterion("RESPONDENT_ANSWER_TIME between", value1, value2,
					"respondentAnswerTime");
			return (Criteria) this;
		}

		public Criteria andRespondentAnswerTimeNotBetween(Date value1,
				Date value2) {
			addCriterion("RESPONDENT_ANSWER_TIME not between", value1, value2,
					"respondentAnswerTime");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andRespondentStatusIsNull() {
			addCriterion("RESPONDENT_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andRespondentStatusIsNotNull() {
			addCriterion("RESPONDENT_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andRespondentStatusEqualTo(String value) {
			addCriterion("RESPONDENT_STATUS =", value, "respondentStatus");
			return (Criteria) this;
		}

		public Criteria andRespondentStatusNotEqualTo(String value) {
			addCriterion("RESPONDENT_STATUS <>", value, "respondentStatus");
			return (Criteria) this;
		}

		public Criteria andRespondentStatusGreaterThan(String value) {
			addCriterion("RESPONDENT_STATUS >", value, "respondentStatus");
			return (Criteria) this;
		}

		public Criteria andRespondentStatusGreaterThanOrEqualTo(String value) {
			addCriterion("RESPONDENT_STATUS >=", value, "respondentStatus");
			return (Criteria) this;
		}

		public Criteria andRespondentStatusLessThan(String value) {
			addCriterion("RESPONDENT_STATUS <", value, "respondentStatus");
			return (Criteria) this;
		}

		public Criteria andRespondentStatusLessThanOrEqualTo(String value) {
			addCriterion("RESPONDENT_STATUS <=", value, "respondentStatus");
			return (Criteria) this;
		}

		public Criteria andRespondentStatusLike(String value) {
			addCriterion("RESPONDENT_STATUS like", value, "respondentStatus");
			return (Criteria) this;
		}

		public Criteria andRespondentStatusNotLike(String value) {
			addCriterion("RESPONDENT_STATUS not like", value,
					"respondentStatus");
			return (Criteria) this;
		}

		public Criteria andRespondentStatusIn(List<String> values) {
			addCriterion("RESPONDENT_STATUS in", values, "respondentStatus");
			return (Criteria) this;
		}

		public Criteria andRespondentStatusNotIn(List<String> values) {
			addCriterion("RESPONDENT_STATUS not in", values, "respondentStatus");
			return (Criteria) this;
		}

		public Criteria andRespondentStatusBetween(String value1, String value2) {
			addCriterion("RESPONDENT_STATUS between", value1, value2,
					"respondentStatus");
			return (Criteria) this;
		}

		public Criteria andRespondentStatusNotBetween(String value1,
				String value2) {
			addCriterion("RESPONDENT_STATUS not between", value1, value2,
					"respondentStatus");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIsNull() {
			addCriterion("CREATER_ID is null");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIsNotNull() {
			addCriterion("CREATER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCreaterIdEqualTo(String value) {
			addCriterion("CREATER_ID =", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotEqualTo(String value) {
			addCriterion("CREATER_ID <>", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdGreaterThan(String value) {
			addCriterion("CREATER_ID >", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdGreaterThanOrEqualTo(String value) {
			addCriterion("CREATER_ID >=", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLessThan(String value) {
			addCriterion("CREATER_ID <", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLessThanOrEqualTo(String value) {
			addCriterion("CREATER_ID <=", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdLike(String value) {
			addCriterion("CREATER_ID like", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotLike(String value) {
			addCriterion("CREATER_ID not like", value, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdIn(List<String> values) {
			addCriterion("CREATER_ID in", values, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotIn(List<String> values) {
			addCriterion("CREATER_ID not in", values, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdBetween(String value1, String value2) {
			addCriterion("CREATER_ID between", value1, value2, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreaterIdNotBetween(String value1, String value2) {
			addCriterion("CREATER_ID not between", value1, value2, "createrId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * quiz_record
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}