package com.zyxy.common.mapper;

import com.zyxy.common.domain.AgentAuthority;
import com.zyxy.common.domain.AgentAuthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgentAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_authority
     *
     * @mbggenerated
     */
    int countByExample(AgentAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_authority
     *
     * @mbggenerated
     */
    int deleteByExample(AgentAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_authority
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_authority
     *
     * @mbggenerated
     */
    int insert(AgentAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_authority
     *
     * @mbggenerated
     */
    int insertSelective(AgentAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_authority
     *
     * @mbggenerated
     */
    List<AgentAuthority> selectByExample(AgentAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_authority
     *
     * @mbggenerated
     */
    AgentAuthority selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_authority
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AgentAuthority record, @Param("example") AgentAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_authority
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AgentAuthority record, @Param("example") AgentAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_authority
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AgentAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_authority
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AgentAuthority record);
}