package com.zyxy.common.mapper;

import com.zyxy.common.domain.AuthorizationDelegate;
import com.zyxy.common.domain.AuthorizationDelegateExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface AuthorizationDelegateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authorization_delegate
	 * @mbggenerated
	 */
	int countByExample(AuthorizationDelegateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authorization_delegate
	 * @mbggenerated
	 */
	int deleteByExample(AuthorizationDelegateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authorization_delegate
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authorization_delegate
	 * @mbggenerated
	 */
	int insert(AuthorizationDelegate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authorization_delegate
	 * @mbggenerated
	 */
	int insertSelective(AuthorizationDelegate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authorization_delegate
	 * @mbggenerated
	 */
	List<AuthorizationDelegate> selectByExample(
			AuthorizationDelegateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authorization_delegate
	 * @mbggenerated
	 */
	AuthorizationDelegate selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authorization_delegate
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") AuthorizationDelegate record,
			@Param("example") AuthorizationDelegateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authorization_delegate
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") AuthorizationDelegate record,
			@Param("example") AuthorizationDelegateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authorization_delegate
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AuthorizationDelegate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table authorization_delegate
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AuthorizationDelegate record);

	int addAuthorizationDelegate(Map params);
	
	/**
	 * 查询用户某审批权限的被授权人
	 * @param userId 用户id
	 * @param authType 授予的审批权限
	 * @return 被授权用户Id
	 */
	String queryAuthorization(@Param("userId")String userId,@Param("authType")String authType);

}