package com.zyxy.common.mapper;

import com.zyxy.common.domain.CaseAvoidRecord;
import com.zyxy.common.domain.CaseAvoidRecordExample;
import com.zyxy.common.domain.CaseAvoidRecordWithBLOBs;

import java.util.List;

import com.zyxy.common.vo.ApproveRecordVO;
import com.zyxy.common.vo.ArbitratorAvoidApplyDocVO;
import com.zyxy.common.vo.ArbitratorAvoidDecisionDocVO;
import com.zyxy.common.vo.ArbitratorAvoidRecordVO;
import com.zyxy.common.vo.AvoidVO;
import com.zyxy.common.vo.SecretaryAvoidApplyDocVO;

import org.apache.ibatis.annotations.Param;

public interface CaseAvoidRecordMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	int countByExample(CaseAvoidRecordExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	int deleteByExample(CaseAvoidRecordExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	int insert(CaseAvoidRecordWithBLOBs record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	int insertSelective(CaseAvoidRecordWithBLOBs record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	List<CaseAvoidRecordWithBLOBs> selectByExampleWithBLOBs(
			CaseAvoidRecordExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	List<CaseAvoidRecord> selectByExample(CaseAvoidRecordExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	CaseAvoidRecordWithBLOBs selectByPrimaryKey(String id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	int updateByExampleSelective(
			@Param("record") CaseAvoidRecordWithBLOBs record,
			@Param("example") CaseAvoidRecordExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	int updateByExampleWithBLOBs(
			@Param("record") CaseAvoidRecordWithBLOBs record,
			@Param("example") CaseAvoidRecordExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") CaseAvoidRecord record,
			@Param("example") CaseAvoidRecordExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CaseAvoidRecordWithBLOBs record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(CaseAvoidRecordWithBLOBs record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_avoid_record
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CaseAvoidRecord record);
	String selectEffectiveArbitratorByCaseId(String caseId);
    /**
     * 查询出审批记录
     * @param caseId
     * @param approveType
     * @param requestType
     * @return
     */
    List<ApproveRecordVO> queryApproveRecord(@Param("caseId") String caseId,@Param("approveType") String approveType,@Param("requestType") String requestType);
    
    /**
     * 查询回避申请书
     * @param busiId 业务Id
     * @return
     */
	AvoidVO queryAvoid(@Param("busiId") String busiId);
	
	/**
	 * 查询仲裁员回避记录
	 * @param caseId
	 * @return
	 */
	List<ArbitratorAvoidRecordVO> selectArbitratorAvoidList(String caseId);
	
	/**
	 * 修改回避状态
	 * @param caseId 案件Id
	 * @param status 回避状态
	 * @return
	 */
	int updateArbitratorStatus(@Param("caseId") String caseId,@Param("status") String status);
	
	/**
	 * 秘书回避申请书
	 * @param avoidId
	 * @return
	 */
	SecretaryAvoidApplyDocVO selectSecretaryAvoidApplyDoc(String avoidId);
	
	/**
	 * 仲裁员回避申请书
	 * @param avoidId
	 * @return
	 */
	ArbitratorAvoidApplyDocVO selectArbitrationApplyDoc(String avoidId);
	
	/**
	 * 仲裁员回避决定书
	 * @param avoidId
	 * @return
	 */
	ArbitratorAvoidDecisionDocVO selectArbitratorAvoidDecisionDoc(String avoidId);

}