package com.zyxy.common.mapper;

import com.zyxy.common.domain.CaseAgentAuthorRecord;
import com.zyxy.common.domain.CaseAgentAuthorRecordExample;
import com.zyxy.common.vo.CaseDraftAgentAuthorVO;
import com.zyxy.common.vo.LitigantAuthorStorageVO;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CaseAgentAuthorRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	int countByExample(CaseAgentAuthorRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	int deleteByExample(CaseAgentAuthorRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	int insert(CaseAgentAuthorRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	int insertSelective(CaseAgentAuthorRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	List<CaseAgentAuthorRecord> selectByExample(
			CaseAgentAuthorRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	CaseAgentAuthorRecord selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") CaseAgentAuthorRecord record,
			@Param("example") CaseAgentAuthorRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") CaseAgentAuthorRecord record,
			@Param("example") CaseAgentAuthorRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CaseAgentAuthorRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_agent_author_record
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CaseAgentAuthorRecord record);
	
	/**
	 * 查询草稿信息
	 * @param caseId
	 * @return
	 */
	CaseDraftAgentAuthorVO selectAgentAuthorInfo(String caseId);
	
	/**
	 * 根据案件Id查询授权缓存信息
	 * @param caseId
	 * @return
	 */
	LitigantAuthorStorageVO selectLitigantAuthorStorage(String caseId);
	
	
}