package com.zyxy.common.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.zyxy.common.domain.CaseEvaluation;
import com.zyxy.common.domain.CaseEvaluationExample;
import com.zyxy.common.dto.CaseEvaluationDTO;
import com.zyxy.common.vo.CaseEvaluationListVO;

public interface CaseEvaluationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_eval
     *
     * @mbggenerated
     */
    int countByExample(CaseEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_eval
     *
     * @mbggenerated
     */
    int deleteByExample(CaseEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_eval
     *
     * @mbggenerated
     */
    int insert(CaseEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_eval
     *
     * @mbggenerated
     */
    int insertSelective(CaseEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_eval
     *
     * @mbggenerated
     */
    List<CaseEvaluation> selectByExampleWithBLOBs(CaseEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_eval
     *
     * @mbggenerated
     */
    List<CaseEvaluation> selectByExample(CaseEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_eval
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CaseEvaluation record, @Param("example") CaseEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_eval
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") CaseEvaluation record, @Param("example") CaseEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_eval
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CaseEvaluation record, @Param("example") CaseEvaluationExample example);
    
    /**
     * 查询案件评价
     * @param formData 表单信息
     * @return 案件的评价内容
     */
    List<CaseEvaluationListVO> queryCaseEvaluation(@Param("dto")CaseEvaluationDTO formData);
}