package com.zyxy.common.mapper;

import com.zyxy.common.domain.CaseRejoinRecord;
import com.zyxy.common.domain.CaseRejoinRecordExample;
import com.zyxy.common.vo.ReplyDocVO;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import com.zyxy.common.domain.CaseRejoinRecordWithBLOBs;

public interface CaseRejoinRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	int countByExample(CaseRejoinRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	int deleteByExample(CaseRejoinRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	int insert(CaseRejoinRecordWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	int insertSelective(CaseRejoinRecordWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	List<CaseRejoinRecordWithBLOBs> selectByExampleWithBLOBs(
			CaseRejoinRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	List<CaseRejoinRecord> selectByExample(CaseRejoinRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	CaseRejoinRecordWithBLOBs selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	int updateByExampleSelective(
			@Param("record") CaseRejoinRecordWithBLOBs record,
			@Param("example") CaseRejoinRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	int updateByExampleWithBLOBs(
			@Param("record") CaseRejoinRecordWithBLOBs record,
			@Param("example") CaseRejoinRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") CaseRejoinRecord record,
			@Param("example") CaseRejoinRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CaseRejoinRecordWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(CaseRejoinRecordWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_rejoin_record
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CaseRejoinRecord record);

	/**
	 * 查询反答辩书
	 * @param caseId
	 * @return
	 */
	ReplyDocVO selectBackRejoinDoc(@Param("caseId") String caseId);
	
	/**
	 * 查询答辩书
	 * @param caseId
	 * @return
	 */
	ReplyDocVO selectRejoinDoc(@Param("caseId") String caseId);
	
	
}