package com.zyxy.common.mapper;

import com.zyxy.common.domain.CaseArbitratorOper;
import com.zyxy.common.domain.CaseArbitratorOperExample;
import com.zyxy.common.vo.ArbitratorPersonalInfoVO;
import com.zyxy.common.vo.LitigantArbitratorInfoVO;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CaseArbitratorOperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_arbitrator_oper
     *
     * @mbggenerated
     */
    int countByExample(CaseArbitratorOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_arbitrator_oper
     *
     * @mbggenerated
     */
    int deleteByExample(CaseArbitratorOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_arbitrator_oper
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_arbitrator_oper
     *
     * @mbggenerated
     */
    int insert(CaseArbitratorOper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_arbitrator_oper
     *
     * @mbggenerated
     */
    int insertSelective(CaseArbitratorOper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_arbitrator_oper
     *
     * @mbggenerated
     */
    List<CaseArbitratorOper> selectByExample(CaseArbitratorOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_arbitrator_oper
     *
     * @mbggenerated
     */
    CaseArbitratorOper selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_arbitrator_oper
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CaseArbitratorOper record, @Param("example") CaseArbitratorOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_arbitrator_oper
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CaseArbitratorOper record, @Param("example") CaseArbitratorOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_arbitrator_oper
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CaseArbitratorOper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_arbitrator_oper
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CaseArbitratorOper record);
    
    /**
     * 根据案件ID查询当事人选择的仲裁员
     * @param caseId
     * @return
     */
    List<LitigantArbitratorInfoVO> selectArbitratorForLitigantByCaseId(String caseId);
}