package com.zyxy.common.mapper;

import com.zyxy.common.domain.CaseJurisDisProcessRecord;
import com.zyxy.common.domain.CaseJurisDisProcessRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CaseJurisDisProcessRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_juris_dis_process_record
	 * @mbggenerated
	 */
	int countByExample(CaseJurisDisProcessRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_juris_dis_process_record
	 * @mbggenerated
	 */
	int deleteByExample(CaseJurisDisProcessRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_juris_dis_process_record
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_juris_dis_process_record
	 * @mbggenerated
	 */
	int insert(CaseJurisDisProcessRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_juris_dis_process_record
	 * @mbggenerated
	 */
	int insertSelective(CaseJurisDisProcessRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_juris_dis_process_record
	 * @mbggenerated
	 */
	List<CaseJurisDisProcessRecord> selectByExample(
			CaseJurisDisProcessRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_juris_dis_process_record
	 * @mbggenerated
	 */
	CaseJurisDisProcessRecord selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_juris_dis_process_record
	 * @mbggenerated
	 */
	int updateByExampleSelective(
			@Param("record") CaseJurisDisProcessRecord record,
			@Param("example") CaseJurisDisProcessRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_juris_dis_process_record
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") CaseJurisDisProcessRecord record,
			@Param("example") CaseJurisDisProcessRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_juris_dis_process_record
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CaseJurisDisProcessRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_juris_dis_process_record
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CaseJurisDisProcessRecord record);
}