package com.zyxy.common.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.zyxy.common.domain.CaseProtocolRecord;
import com.zyxy.common.domain.CaseProtocolRecordExample;
import com.zyxy.common.domain.CaseProtocolRecordWithBLOBs;
import com.zyxy.common.vo.CaseProtocolRecordVO;

public interface CaseProtocolRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_protocol_record
	 * @mbggenerated
	 */
	int countByExample(CaseProtocolRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_protocol_record
	 * @mbggenerated
	 */
	int deleteByExample(CaseProtocolRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_protocol_record
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_protocol_record
	 * @mbggenerated
	 */
	int insert(CaseProtocolRecordWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_protocol_record
	 * @mbggenerated
	 */
	int insertSelective(CaseProtocolRecordWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_protocol_record
	 * @mbggenerated
	 */
	List<CaseProtocolRecordWithBLOBs> selectByExampleWithBLOBs(
			CaseProtocolRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_protocol_record
	 * @mbggenerated
	 */
	List<CaseProtocolRecord> selectByExample(CaseProtocolRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_protocol_record
	 * @mbggenerated
	 */
	CaseProtocolRecordWithBLOBs selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_protocol_record
	 * @mbggenerated
	 */
	int updateByExampleSelective(
			@Param("record") CaseProtocolRecordWithBLOBs record,
			@Param("example") CaseProtocolRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_protocol_record
	 * @mbggenerated
	 */
	int updateByExampleWithBLOBs(
			@Param("record") CaseProtocolRecordWithBLOBs record,
			@Param("example") CaseProtocolRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_protocol_record
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") CaseProtocolRecord record,
			@Param("example") CaseProtocolRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_protocol_record
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CaseProtocolRecordWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_protocol_record
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(CaseProtocolRecordWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table case_protocol_record
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CaseProtocolRecord record);

	/**
	 * 根据案件ID、申请类型查询调解协议
	 * @param caseProtocolRecord 
	 */
	CaseProtocolRecordVO selectCaseProtocolRecord(CaseProtocolRecord caseProtocolRecord);
}