package com.zyxy.common.mapper;

import com.zyxy.common.domain.ContraryToAccount;
import com.zyxy.common.domain.ContraryToAccountExample;
import com.zyxy.common.dto.ContraryAuditDTO;
import com.zyxy.common.vo.ContraryAuditVO;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ContraryToAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contrary_to_account
     *
     * @mbggenerated
     */
    int countByExample(ContraryToAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contrary_to_account
     *
     * @mbggenerated
     */
    int deleteByExample(ContraryToAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contrary_to_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contrary_to_account
     *
     * @mbggenerated
     */
    int insert(ContraryToAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contrary_to_account
     *
     * @mbggenerated
     */
    int insertSelective(ContraryToAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contrary_to_account
     *
     * @mbggenerated
     */
    List<ContraryToAccount> selectByExample(ContraryToAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contrary_to_account
     *
     * @mbggenerated
     */
    ContraryToAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contrary_to_account
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ContraryToAccount record, @Param("example") ContraryToAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contrary_to_account
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ContraryToAccount record, @Param("example") ContraryToAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contrary_to_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ContraryToAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contrary_to_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ContraryToAccount record);

    /**
     * 查询对公账户审核列表
     * @param formData
     */
	List<ContraryAuditVO> queryContraryAuditList(ContraryAuditDTO formData);

	/**
	 * 审核对公账户-修改状态
	 * @param id
	 * @param value
	 * @return
	 */
	int updateContraryAudit(@Param("id") String id, @Param("status") String status);
}