package com.zyxy.common.mapper;

import com.zyxy.common.domain.DocSendRecord;
import com.zyxy.common.domain.DocSendRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DocSendRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_send_record
     *
     * @mbggenerated
     */
    int countByExample(DocSendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_send_record
     *
     * @mbggenerated
     */
    int deleteByExample(DocSendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_send_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_send_record
     *
     * @mbggenerated
     */
    int insert(DocSendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_send_record
     *
     * @mbggenerated
     */
    int insertSelective(DocSendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_send_record
     *
     * @mbggenerated
     */
    List<DocSendRecord> selectByExample(DocSendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_send_record
     *
     * @mbggenerated
     */
    DocSendRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_send_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DocSendRecord record, @Param("example") DocSendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_send_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DocSendRecord record, @Param("example") DocSendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_send_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DocSendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_send_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DocSendRecord record);


    /*********手动添加的方法**********/
    /**
     * 仲裁委查询文书出具人类型  0-仲裁秘书 1-仲裁员
     * @param busiId 业务id
     * @return 出具人类型
     */
    String arbitrationQueryDocIssuer(String busiId);


    /**
     * 批量插入文件下发记录
     * @param list
     * @return
     */
    int batchInsertDocSendRecord(List<DocSendRecord> list);
    
    /**
     * 通过请求id查询案件初次受理时间
     * @param requestId 请求id
     * @return 案件初次受理时间
     */
    String selectAcceptTimeByRequestId(String requestId);
}