package com.zyxy.common.mapper;

import com.zyxy.common.domain.DataStatistics;
import com.zyxy.common.domain.ManagerInfo;
import com.zyxy.common.domain.ManagerInfoExample;
import java.util.List;

import com.zyxy.common.dto.DataStatisticsDTO;
import org.apache.ibatis.annotations.Param;

public interface ManagerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbggenerated
     */
    long countByExample(ManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbggenerated
     */
    int deleteByExample(ManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbggenerated
     */
    int insert(ManagerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbggenerated
     */
    int insertSelective(ManagerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbggenerated
     */
    List<ManagerInfo> selectByExample(ManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbggenerated
     */
    ManagerInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ManagerInfo record, @Param("example") ManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ManagerInfo record, @Param("example") ManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManagerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManagerInfo record);

    /******手动增加的方法******/

    /**
     * 根据sys_user表中的id查询出仲裁委工作人员的职务以及状态
     * @param userId
     * @return
     */
    ManagerInfo queryDutiesAndStatusByPrimaryKey(String userId);


    /**
     * 数据统计
     * @param formData
     * @return
     */
    DataStatistics queryDataStatistics(DataStatisticsDTO formData);
    
    /**
     * 通过用户id查询仲裁委人员职务
     * @param userId 用户id
     * @return 职位
     */
    String queryDutiesByUserId(String userId);
}