package com.zyxy.common.mapper;

import com.zyxy.common.domain.PayOrderTran;
import com.zyxy.common.domain.PayOrderTranExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayOrderTranMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_tran
     *
     * @mbggenerated
     */
    int countByExample(PayOrderTranExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_tran
     *
     * @mbggenerated
     */
    int deleteByExample(PayOrderTranExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_tran
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_tran
     *
     * @mbggenerated
     */
    int insert(PayOrderTran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_tran
     *
     * @mbggenerated
     */
    int insertSelective(PayOrderTran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_tran
     *
     * @mbggenerated
     */
    List<PayOrderTran> selectByExample(PayOrderTranExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_tran
     *
     * @mbggenerated
     */
    PayOrderTran selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_tran
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PayOrderTran record, @Param("example") PayOrderTranExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_tran
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PayOrderTran record, @Param("example") PayOrderTranExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_tran
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PayOrderTran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_tran
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PayOrderTran record);

    long selectSumAmountByCaseId(String caseId);
}