package com.zyxy.common.mapper;

import com.zyxy.common.domain.QuizRecord;
import com.zyxy.common.domain.QuizRecordExample;
import com.zyxy.common.domain.QuizRecordWithBLOBs;
import com.zyxy.common.dto.QuestionInfoDTO;
import com.zyxy.common.dto.QuizRecordDTO;

import java.util.List;

import com.zyxy.common.vo.CaseQuizRecordVO;
import com.zyxy.common.vo.QuizRecordVO;

import org.apache.ibatis.annotations.Param;

public interface QuizRecordMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	int countByExample(QuizRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	int deleteByExample(QuizRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	int insert(QuizRecordWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	int insertSelective(QuizRecordWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	List<QuizRecordWithBLOBs> selectByExampleWithBLOBs(QuizRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	List<QuizRecord> selectByExample(QuizRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	QuizRecordWithBLOBs selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") QuizRecordWithBLOBs record,
			@Param("example") QuizRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	int updateByExampleWithBLOBs(@Param("record") QuizRecordWithBLOBs record,
			@Param("example") QuizRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") QuizRecord record,
			@Param("example") QuizRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(QuizRecordWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(QuizRecordWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table quiz_record
	 * @mbggenerated
	 */
	int updateByPrimaryKey(QuizRecord record);

	/**
     *
     * @param caseId
     * @return
     */
    List<CaseQuizRecordVO> queryByCaseId(String caseId);
    
    /**
     * 插入问题记录
     * @param formData
     * @return
     */
    int insertQuizRecord(@Param("list") List<QuestionInfoDTO> quizRecords,
    		@Param("caseId") String caseId,@Param("userId") String userId);
    
    /**
     * 申请方回答
     * @param quizRecords
     * @return
     */
    int updateProposerQuizRecord(@Param("list") List<QuizRecordDTO> quizRecords,@Param("status") String status);
    
    /**
     * 被申请方回答
     * @param quizRecords
     * @return
     */
    int updateDefendantQuizRecord(@Param("list") List<QuizRecordDTO> quizRecords,@Param("status") String status);
    
    List<QuizRecordVO> selectQuizRecord(String caseId);
}