package com.zyxy.common.mapper;

import com.zyxy.common.domain.QuizAnswerRecord;
import com.zyxy.common.domain.QuizAnswerRecordExample;
import com.zyxy.common.vo.QuizAnswerVO;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface QuizAnswerRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_answer_record
     *
     * @mbggenerated
     */
    int countByExample(QuizAnswerRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_answer_record
     *
     * @mbggenerated
     */
    int deleteByExample(QuizAnswerRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_answer_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_answer_record
     *
     * @mbggenerated
     */
    int insert(QuizAnswerRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_answer_record
     *
     * @mbggenerated
     */
    int insertSelective(QuizAnswerRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_answer_record
     *
     * @mbggenerated
     */
    List<QuizAnswerRecord> selectByExampleWithBLOBs(QuizAnswerRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_answer_record
     *
     * @mbggenerated
     */
    List<QuizAnswerRecord> selectByExample(QuizAnswerRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_answer_record
     *
     * @mbggenerated
     */
    QuizAnswerRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_answer_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QuizAnswerRecord record, @Param("example") QuizAnswerRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_answer_record
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") QuizAnswerRecord record, @Param("example") QuizAnswerRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_answer_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") QuizAnswerRecord record, @Param("example") QuizAnswerRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_answer_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuizAnswerRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_answer_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(QuizAnswerRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz_answer_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuizAnswerRecord record);
    
    /**
     * 根据问题quizId和回答人类型查询问题回答 
     * @param quziId
     * @param answerType
     * @return
     */
    List<QuizAnswerVO> selectQuizAnswer(@Param("quizId")String quziId,@Param("answerType")String answerType);
}